package com.ss.android.ugc.playerkit.simapicommon.a;

import com.bytedance.covode.number.Covode;
import h.f.b.g;
import h.f.b.l;
import java.io.Serializable;

public final class a implements Serializable {
    private final String captionFormat;
    private final long complaintId;
    private final long createTime;
    private final long expire;
    private final int id;
    private final boolean isAutoGenerated;
    private final String lang;
    private final long languageId;
    private final int subId;
    private final String subVersion;
    private String uri;
    private final String url;

    static {
        Covode.recordClassIndex(98027);
    }

    public static int com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode(int i2) {
        return i2;
    }

    public static int com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode(long j2) {
        return (int) (j2 ^ (j2 >>> 32));
    }

    public static /* synthetic */ a copy$default(a aVar, long j2, String str, String str2, int i2, String str3, String str4, long j3, boolean z, long j4, long j5, int i3, String str5, int i4, Object obj) {
        String str6 = str;
        long j6 = j2;
        String str7 = str3;
        int i5 = i2;
        String str8 = str2;
        long j7 = j3;
        String str9 = str4;
        long j8 = j4;
        boolean z2 = z;
        long j9 = j5;
        String str10 = str5;
        int i6 = i3;
        if ((i4 & 1) != 0) {
            j6 = aVar.expire;
        }
        if ((i4 & 2) != 0) {
            str6 = aVar.captionFormat;
        }
        if ((i4 & 4) != 0) {
            str8 = aVar.lang;
        }
        if ((i4 & 8) != 0) {
            i5 = aVar.subId;
        }
        if ((i4 & 16) != 0) {
            str7 = aVar.subVersion;
        }
        if ((i4 & 32) != 0) {
            str9 = aVar.url;
        }
        if ((i4 & 64) != 0) {
            j7 = aVar.languageId;
        }
        if ((i4 & 128) != 0) {
            z2 = aVar.isAutoGenerated;
        }
        if ((i4 & 256) != 0) {
            j8 = aVar.complaintId;
        }
        if ((i4 & 512) != 0) {
            j9 = aVar.createTime;
        }
        if ((i4 & 1024) != 0) {
            i6 = aVar.id;
        }
        if ((i4 & 2048) != 0) {
            str10 = aVar.uri;
        }
        return aVar.copy(j6, str6, str8, i5, str7, str9, j7, z2, j8, j9, i6, str10);
    }

    public final long component1() {
        return this.expire;
    }

    public final long component10() {
        return this.createTime;
    }

    public final int component11() {
        return this.id;
    }

    public final String component12() {
        return this.uri;
    }

    public final String component2() {
        return this.captionFormat;
    }

    public final String component3() {
        return this.lang;
    }

    public final int component4() {
        return this.subId;
    }

    public final String component5() {
        return this.subVersion;
    }

    public final String component6() {
        return this.url;
    }

    public final long component7() {
        return this.languageId;
    }

    public final boolean component8() {
        return this.isAutoGenerated;
    }

    public final long component9() {
        return this.complaintId;
    }

    public final a copy(long j2, String str, String str2, int i2, String str3, String str4, long j3, boolean z, long j4, long j5, int i3, String str5) {
        l.c(str, "");
        l.c(str2, "");
        l.c(str3, "");
        l.c(str4, "");
        return new a(j2, str, str2, i2, str3, str4, j3, z, j4, j5, i3, str5);
    }

    public final boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof a)) {
            return false;
        }
        a aVar = (a) obj;
        return this.expire == aVar.expire && l.a(this.captionFormat, aVar.captionFormat) && l.a(this.lang, aVar.lang) && this.subId == aVar.subId && l.a(this.subVersion, aVar.subVersion) && l.a(this.url, aVar.url) && this.languageId == aVar.languageId && this.isAutoGenerated == aVar.isAutoGenerated && this.complaintId == aVar.complaintId && this.createTime == aVar.createTime && this.id == aVar.id && l.a(this.uri, aVar.uri);
    }

    public final int hashCode() {
        int com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode = com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode(this.expire) * 31;
        String str = this.captionFormat;
        int i2 = 0;
        int hashCode = (com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode + (str != null ? str.hashCode() : 0)) * 31;
        String str2 = this.lang;
        int hashCode2 = (((hashCode + (str2 != null ? str2.hashCode() : 0)) * 31) + com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode(this.subId)) * 31;
        String str3 = this.subVersion;
        int hashCode3 = (hashCode2 + (str3 != null ? str3.hashCode() : 0)) * 31;
        String str4 = this.url;
        int hashCode4 = (((hashCode3 + (str4 != null ? str4.hashCode() : 0)) * 31) + com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode(this.languageId)) * 31;
        boolean z = this.isAutoGenerated;
        if (z) {
            z = true;
        }
        int i3 = z ? 1 : 0;
        int i4 = z ? 1 : 0;
        int i5 = z ? 1 : 0;
        int com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode2 = (((((((hashCode4 + i3) * 31) + com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode(this.complaintId)) * 31) + com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode(this.createTime)) * 31) + com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode(this.id)) * 31;
        String str5 = this.uri;
        if (str5 != null) {
            i2 = str5.hashCode();
        }
        return com_ss_android_ugc_playerkit_simapicommon_model_CaptionInfo_com_ss_android_ugc_aweme_lancet_HashCodeLancet_hashCode2 + i2;
    }

    public final String toString() {
        return "CaptionInfo(expire=" + this.expire + ", captionFormat=" + this.captionFormat + ", lang=" + this.lang + ", subId=" + this.subId + ", subVersion=" + this.subVersion + ", url=" + this.url + ", languageId=" + this.languageId + ", isAutoGenerated=" + this.isAutoGenerated + ", complaintId=" + this.complaintId + ", createTime=" + this.createTime + ", id=" + this.id + ", uri=" + this.uri + ")";
    }

    public final String getCaptionFormat() {
        return this.captionFormat;
    }

    public final long getComplaintId() {
        return this.complaintId;
    }

    public final long getCreateTime() {
        return this.createTime;
    }

    public final long getExpire() {
        return this.expire;
    }

    public final int getId() {
        return this.id;
    }

    public final String getLang() {
        return this.lang;
    }

    public final long getLanguageId() {
        return this.languageId;
    }

    public final int getSubId() {
        return this.subId;
    }

    public final String getSubVersion() {
        return this.subVersion;
    }

    public final String getUri() {
        return this.uri;
    }

    public final String getUrl() {
        return this.url;
    }

    public final boolean isAutoGenerated() {
        return this.isAutoGenerated;
    }

    public final void setUri(String str) {
        this.uri = str;
    }

    public a(long j2, String str, String str2, int i2, String str3, String str4, long j3, boolean z, long j4, long j5, int i3, String str5) {
        l.c(str, "");
        l.c(str2, "");
        l.c(str3, "");
        l.c(str4, "");
        this.expire = j2;
        this.captionFormat = str;
        this.lang = str2;
        this.subId = i2;
        this.subVersion = str3;
        this.url = str4;
        this.languageId = j3;
        this.isAutoGenerated = z;
        this.complaintId = j4;
        this.createTime = j5;
        this.id = i3;
        this.uri = str5;
    }

    /* JADX INFO: this call moved to the top of the method (can break code semantics) */
    public /* synthetic */ a(long j2, String str, String str2, int i2, String str3, String str4, long j3, boolean z, long j4, long j5, int i3, String str5, int i4, g gVar) {
        this(j2, str, str2, i2, str3, str4, j3, z, j4, j5, i3, (i4 & 2048) != 0 ? null : str5);
    }
}
