package com.ss.ttvideoengine.h;

import com.bytedance.covode.number.Covode;
import com.ss.ttvideoengine.s.j;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import org.json.JSONObject;

public final class z {
    public int A;
    public int B;
    public ArrayList C;
    public int D;
    public int E;
    public int F;
    public int G;
    public int H;
    public String I;
    public String J;
    public int K;
    public int L;
    public int M;
    public int N;
    public int O;
    public int P;
    public String Q;
    public String R;
    public String S;
    public String T;
    public String U;
    public String V;
    public String W;
    public String X;
    public int Y;
    public int Z;

    /* renamed from: a  reason: collision with root package name */
    public long f152819a;
    public long aA;
    public String aB;
    public int aC;
    public int aD;
    public int aE;
    public String aF;
    public String aG;
    public int aH;
    public int aI;
    public String aJ;
    public Map aK;
    public int aL;
    public int aM;
    public int aN;
    public int aO;
    public int aP;
    public int aQ;
    public int aR;
    public int aS;
    public String aT;
    public String aU;
    public long aV;
    public long aW;
    public int aX;
    public int aY;
    public int aZ;
    public String aa;
    public int ab;
    public int ac;
    public Map ad;
    public long ae;
    public long af;
    public long ag;
    public long ah;
    public long ai;
    public long aj;
    public long ak;
    public long al;
    public long am;
    public long an;
    public long ao;
    public long ap;
    public long aq;
    public long ar;
    public float as;
    public float at;
    public long au;
    public int av;
    public long aw;
    public long ax;
    public long ay;
    public long az;

    /* renamed from: b  reason: collision with root package name */
    public long f152820b;
    public long bA;
    public Map bB;
    public Map bC;
    public int bD;
    public int bE;
    public int bF;
    public int bG;
    public long bH;
    public long bI;
    public long bJ;
    public long bK;
    public long bL;
    public long bM;
    public int bN;
    public long bO;
    public String bP;
    public int bQ;
    public int bR;
    public int bS;
    public int bT;
    public long bU;
    public long bV;
    public int bW;
    public int bX;
    public int bY;
    public int bZ;
    public String ba;
    public String bb;
    public String bc;
    public int bd;
    public int be;
    public int bf;
    public int bg;
    public int bh;
    public int bi;
    public int bj;
    public int bk;
    public String bl;
    public String bm;
    public int bn;
    public int bo;
    public String bp;
    public int bq;
    public int br;
    public String bs;
    public String bt;
    public int bu;
    public int bv;
    public int bw;
    public int bx;
    public long by;
    public long bz;

    /* renamed from: c  reason: collision with root package name */
    public long f152821c;
    public int cA;
    public int cB;
    public boolean cC;
    public boolean cD;
    public int cE;
    public int cF;
    public int cG;
    public int cH;
    public String cI;
    public String cJ;
    public String cK;
    public int cL;
    public int cM;
    public long cN;
    public long cO;
    public Map<String, String> cP;
    public Map<String, String> cQ;
    public ArrayList<Float> cR;
    public Map<String, String> cS;
    public Map<String, Integer> cT;
    public ArrayList<Integer> cU;
    public ArrayList<Integer> cV;
    public int cW;
    public int cX;
    public int cY;
    public Map cZ;
    public long ca;
    public long cb;
    public long cc;
    public double cd;
    public double ce;
    public int cf;
    public int cg;
    public String ch;
    public int ci;
    public int cj;
    public long ck;
    public long cl;
    public long cm;
    public long cn;
    public int co;
    public long cp;
    public long cq;
    public long cr;
    public long cs;
    public long ct;
    public long cu;
    public int cv;
    public long cw;
    public int cx;
    public int cy;
    public int cz;

    /* renamed from: d  reason: collision with root package name */
    public long f152822d;
    public long dA;
    public int dB;
    public int dC;
    public int dD;
    public int dE;
    public int dF;
    public int dG;
    public int dH;
    public String dI;
    public String dJ;
    public String dK;
    public int dL;
    public int dM;
    public int dN;
    public int dO;
    public int dP;
    public float dQ;
    public float dR;
    public float dS;
    public float dT;
    public ArrayList<String> dU;
    public ArrayList<String> dV;
    public ArrayList<String> dW;
    public ArrayList<String> dX;
    public boolean dY;
    public int dZ;
    public long da;
    public long db;
    public long dc;
    public long dd;
    public long de;
    public ArrayList<String> df;
    public ArrayList<String> dg;
    public ArrayList<String> dh;
    public ArrayList<String> di;
    public ArrayList<String> dj;
    public ArrayList<String> dk;
    public ArrayList<String> dl;
    public ArrayList<String> dm;
    public ArrayList<String> dn;

    /* renamed from: do  reason: not valid java name */
    public ArrayList<String> f350do;
    public ArrayList<String> dp;
    public ArrayList<String> dq;
    public ArrayList<String> dr;
    public ArrayList<Integer> ds;
    public ArrayList<Integer> dt;
    public ArrayList<String> du;
    public ArrayList dv;
    public int dw;
    public long dx;
    public long dy;
    public long dz;

    /* renamed from: e  reason: collision with root package name */
    public long f152823e;
    public String ea;

    /* renamed from: f  reason: collision with root package name */
    public long f152824f;

    /* renamed from: g  reason: collision with root package name */
    public long f152825g;

    /* renamed from: h  reason: collision with root package name */
    public long f152826h;

    /* renamed from: i  reason: collision with root package name */
    public long f152827i;

    /* renamed from: j  reason: collision with root package name */
    public long f152828j;

    /* renamed from: k  reason: collision with root package name */
    public long f152829k;

    /* renamed from: l  reason: collision with root package name */
    public long f152830l;

    /* renamed from: m  reason: collision with root package name */
    public long f152831m;
    public long n;
    public long o;
    public long p;
    public long q;
    public long r;
    public long s;
    public long t;
    public long u;
    public long v;
    public long w;
    public long x;
    public long y;
    public long z;

    static {
        Covode.recordClassIndex(101648);
    }

    z() {
        this.f152819a = -2147483648L;
        this.f152820b = -2147483648L;
        this.f152821c = -2147483648L;
        this.f152822d = -2147483648L;
        this.f152823e = -2147483648L;
        this.f152824f = -2147483648L;
        this.f152825g = -2147483648L;
        this.f152826h = -2147483648L;
        this.f152827i = -2147483648L;
        this.f152828j = -2147483648L;
        this.f152829k = -2147483648L;
        this.f152830l = -2147483648L;
        this.f152831m = -2147483648L;
        this.n = -2147483648L;
        this.o = -2147483648L;
        this.p = -2147483648L;
        this.q = -2147483648L;
        this.r = -2147483648L;
        this.s = -2147483648L;
        this.t = -2147483648L;
        this.u = -2147483648L;
        this.v = -2147483648L;
        this.w = -2147483648L;
        this.x = -2147483648L;
        this.y = -2147483648L;
        this.z = -2147483648L;
        this.A = Integer.MIN_VALUE;
        this.B = Integer.MIN_VALUE;
        this.C = new ArrayList();
        this.D = Integer.MIN_VALUE;
        this.E = Integer.MIN_VALUE;
        this.F = Integer.MIN_VALUE;
        this.G = Integer.MIN_VALUE;
        this.H = Integer.MIN_VALUE;
        this.I = "";
        this.J = "";
        this.K = Integer.MIN_VALUE;
        this.L = Integer.MIN_VALUE;
        this.M = Integer.MIN_VALUE;
        this.N = Integer.MIN_VALUE;
        this.O = Integer.MIN_VALUE;
        this.P = Integer.MIN_VALUE;
        this.Q = "";
        this.R = "";
        this.S = "";
        this.T = "";
        this.U = "";
        this.V = "";
        this.W = "";
        this.X = "";
        this.Y = Integer.MIN_VALUE;
        this.Z = Integer.MIN_VALUE;
        this.aa = "";
        this.ab = Integer.MIN_VALUE;
        this.ac = Integer.MIN_VALUE;
        this.ad = null;
        this.ae = -2147483648L;
        this.af = -2147483648L;
        this.ag = -2147483648L;
        this.ah = -2147483648L;
        this.ai = -2147483648L;
        this.aj = -2147483648L;
        this.ak = -2147483648L;
        this.al = -2147483648L;
        this.am = -2147483648L;
        this.an = -2147483648L;
        this.ao = -2147483648L;
        this.ap = -2147483648L;
        this.aq = -2147483648L;
        this.ar = -2147483648L;
        this.as = Float.MIN_VALUE;
        this.at = Float.MIN_VALUE;
        this.au = -2147483648L;
        this.av = Integer.MIN_VALUE;
        this.aw = -2147483648L;
        this.ax = -2147483648L;
        this.ay = -2147483648L;
        this.az = -2147483648L;
        this.aA = -2147483648L;
        this.aB = "";
        this.aC = Integer.MIN_VALUE;
        this.aD = Integer.MIN_VALUE;
        this.aE = Integer.MIN_VALUE;
        this.aF = "";
        this.aG = "";
        this.aH = Integer.MIN_VALUE;
        this.aI = Integer.MIN_VALUE;
        this.aJ = "";
        this.aK = null;
        this.aL = Integer.MIN_VALUE;
        this.aM = Integer.MIN_VALUE;
        this.aN = Integer.MIN_VALUE;
        this.aO = Integer.MIN_VALUE;
        this.aP = Integer.MIN_VALUE;
        this.aQ = Integer.MIN_VALUE;
        this.aR = Integer.MIN_VALUE;
        this.aS = Integer.MIN_VALUE;
        this.aT = "";
        this.aU = "";
        this.aV = -2147483648L;
        this.aW = -2147483648L;
        this.aX = Integer.MIN_VALUE;
        this.aY = Integer.MIN_VALUE;
        this.aZ = Integer.MIN_VALUE;
        this.ba = "";
        this.bb = "";
        this.bc = "";
        this.bd = Integer.MIN_VALUE;
        this.be = Integer.MIN_VALUE;
        this.bf = Integer.MIN_VALUE;
        this.bg = Integer.MIN_VALUE;
        this.bh = Integer.MIN_VALUE;
        this.bi = Integer.MIN_VALUE;
        this.bj = Integer.MIN_VALUE;
        this.bk = Integer.MIN_VALUE;
        this.bn = Integer.MIN_VALUE;
        this.bo = Integer.MIN_VALUE;
        this.bp = "";
        this.bq = Integer.MIN_VALUE;
        this.br = Integer.MIN_VALUE;
        this.bs = "";
        this.bt = "";
        this.bu = Integer.MIN_VALUE;
        this.bv = Integer.MIN_VALUE;
        this.bw = Integer.MIN_VALUE;
        this.bx = Integer.MIN_VALUE;
        this.by = -2147483648L;
        this.bz = -2147483648L;
        this.bA = -2147483648L;
        this.bD = -1002;
        this.bE = Integer.MIN_VALUE;
        this.bF = Integer.MIN_VALUE;
        this.bG = Integer.MIN_VALUE;
        this.bH = -2147483648L;
        this.bI = -2147483648L;
        this.bJ = -2147483648L;
        this.bK = -2147483648L;
        this.bL = -2147483648L;
        this.bM = -2147483648L;
        this.bN = Integer.MIN_VALUE;
        this.bO = -2147483648L;
        this.bP = null;
        this.bQ = -1;
        this.bR = -1;
        this.bS = -1;
        this.bT = -1;
        this.bU = -2147483648L;
        this.bV = -2147483648L;
        this.bW = Integer.MIN_VALUE;
        this.bX = Integer.MIN_VALUE;
        this.bY = Integer.MIN_VALUE;
        this.bZ = Integer.MIN_VALUE;
        this.ca = 0;
        this.cb = 0;
        this.cc = 0;
        this.cd = -2.147483648E9d;
        this.ce = -2.147483648E9d;
        this.cf = Integer.MIN_VALUE;
        this.cg = Integer.MIN_VALUE;
        this.ch = "";
        this.ci = Integer.MIN_VALUE;
        this.cj = Integer.MIN_VALUE;
        this.ck = -2147483648L;
        this.cl = -2147483648L;
        this.cm = 0;
        this.cn = 0;
        this.co = 0;
        this.cp = 0;
        this.cq = 0;
        this.cr = 0;
        this.cs = 0;
        this.ct = 0;
        this.cu = 0;
        this.cv = Integer.MIN_VALUE;
        this.cw = -2147483648L;
        this.cx = Integer.MIN_VALUE;
        this.cy = Integer.MIN_VALUE;
        this.cz = Integer.MIN_VALUE;
        this.cA = Integer.MIN_VALUE;
        this.cB = 0;
        this.cC = false;
        this.cD = false;
        this.cE = 0;
        this.cF = 0;
        this.cG = 0;
        this.cH = 0;
        this.cI = "";
        this.cJ = "";
        this.cK = "";
        this.cL = Integer.MIN_VALUE;
        this.cM = Integer.MIN_VALUE;
        this.cN = -2147483648L;
        this.cO = -2147483648L;
        this.cP = null;
        this.cQ = null;
        this.cR = null;
        this.cS = null;
        this.cT = null;
        this.cU = null;
        this.cV = null;
        this.cW = -1;
        this.cX = 0;
        this.cY = -1;
        this.cZ = null;
        this.da = -2147483648L;
        this.db = -2147483648L;
        this.dc = -2147483648L;
        this.dd = -2147483648L;
        this.de = -2147483648L;
        this.df = null;
        this.dg = null;
        this.dh = null;
        this.di = null;
        this.dj = null;
        this.dk = null;
        this.dl = null;
        this.dm = null;
        this.dn = null;
        this.f350do = null;
        this.dp = null;
        this.dq = null;
        this.dr = null;
        this.ds = null;
        this.dt = null;
        this.du = null;
        this.dv = null;
        this.dw = Integer.MIN_VALUE;
        this.dx = -2147483648L;
        this.dy = -2147483648L;
        this.dz = -2147483648L;
        this.dA = -2147483648L;
        this.dB = Integer.MIN_VALUE;
        this.dC = Integer.MIN_VALUE;
        this.dD = Integer.MIN_VALUE;
        this.dE = Integer.MIN_VALUE;
        this.dF = Integer.MIN_VALUE;
        this.dG = Integer.MIN_VALUE;
        this.dH = Integer.MIN_VALUE;
        this.dI = "";
        this.dJ = "";
        this.dK = "";
        this.dL = Integer.MIN_VALUE;
        this.dM = -1;
        this.dN = Integer.MIN_VALUE;
        this.dO = Integer.MIN_VALUE;
        this.dP = Integer.MIN_VALUE;
        this.dQ = Float.MIN_VALUE;
        this.dR = Float.MIN_VALUE;
        this.dS = Float.MIN_VALUE;
        this.dT = Float.MIN_VALUE;
        this.dU = null;
        this.dV = null;
        this.dW = null;
        this.dX = null;
        this.dY = false;
        this.dZ = Integer.MIN_VALUE;
        this.cT = new LinkedHashMap();
        this.cS = new LinkedHashMap();
        this.cU = new ArrayList<>();
        this.cV = new ArrayList<>();
        this.cR = new ArrayList<>();
        this.cP = new LinkedHashMap();
        this.cQ = new LinkedHashMap();
        this.cZ = new HashMap();
    }

    static String a(Map map) {
        if (map == null) {
            return null;
        }
        try {
            if (!map.isEmpty()) {
                return new JSONObject(map).toString();
            }
            return null;
        } catch (Exception e2) {
            j.e("VideoEventOnePlay", e2.toString() + ", :" + map);
            return null;
        }
    }
}
