package com.ss.android.ugc.aweme.tux.a.d;

import com.bytedance.covode.number.Covode;
import com.bytedance.i.a.Cdo;
import com.bytedance.i.a.Cif;
import com.bytedance.i.a.ab;
import com.bytedance.i.a.ac;
import com.bytedance.i.a.ad;
import com.bytedance.i.a.ae;
import com.bytedance.i.a.af;
import com.bytedance.i.a.ag;
import com.bytedance.i.a.ah;
import com.bytedance.i.a.ai;
import com.bytedance.i.a.aj;
import com.bytedance.i.a.ak;
import com.bytedance.i.a.al;
import com.bytedance.i.a.am;
import com.bytedance.i.a.an;
import com.bytedance.i.a.ao;
import com.bytedance.i.a.ap;
import com.bytedance.i.a.aq;
import com.bytedance.i.a.ar;
import com.bytedance.i.a.as;
import com.bytedance.i.a.at;
import com.bytedance.i.a.au;
import com.bytedance.i.a.av;
import com.bytedance.i.a.aw;
import com.bytedance.i.a.ax;
import com.bytedance.i.a.ay;
import com.bytedance.i.a.az;
import com.bytedance.i.a.ba;
import com.bytedance.i.a.bb;
import com.bytedance.i.a.bc;
import com.bytedance.i.a.bd;
import com.bytedance.i.a.be;
import com.bytedance.i.a.bf;
import com.bytedance.i.a.bg;
import com.bytedance.i.a.bh;
import com.bytedance.i.a.bi;
import com.bytedance.i.a.bj;
import com.bytedance.i.a.bk;
import com.bytedance.i.a.bl;
import com.bytedance.i.a.bm;
import com.bytedance.i.a.bn;
import com.bytedance.i.a.bo;
import com.bytedance.i.a.bp;
import com.bytedance.i.a.bq;
import com.bytedance.i.a.br;
import com.bytedance.i.a.bs;
import com.bytedance.i.a.bt;
import com.bytedance.i.a.bu;
import com.bytedance.i.a.bv;
import com.bytedance.i.a.bw;
import com.bytedance.i.a.bx;
import com.bytedance.i.a.by;
import com.bytedance.i.a.bz;
import com.bytedance.i.a.c;
import com.bytedance.i.a.ca;
import com.bytedance.i.a.cb;
import com.bytedance.i.a.cc;
import com.bytedance.i.a.cd;
import com.bytedance.i.a.ce;
import com.bytedance.i.a.cf;
import com.bytedance.i.a.cg;
import com.bytedance.i.a.ch;
import com.bytedance.i.a.ci;
import com.bytedance.i.a.cj;
import com.bytedance.i.a.ck;
import com.bytedance.i.a.cl;
import com.bytedance.i.a.cm;
import com.bytedance.i.a.cn;
import com.bytedance.i.a.co;
import com.bytedance.i.a.cp;
import com.bytedance.i.a.cq;
import com.bytedance.i.a.cr;
import com.bytedance.i.a.cs;
import com.bytedance.i.a.ct;
import com.bytedance.i.a.cu;
import com.bytedance.i.a.cv;
import com.bytedance.i.a.cw;
import com.bytedance.i.a.cx;
import com.bytedance.i.a.cy;
import com.bytedance.i.a.cz;
import com.bytedance.i.a.d;
import com.bytedance.i.a.da;
import com.bytedance.i.a.db;
import com.bytedance.i.a.dc;
import com.bytedance.i.a.dd;
import com.bytedance.i.a.de;
import com.bytedance.i.a.df;
import com.bytedance.i.a.dg;
import com.bytedance.i.a.dh;
import com.bytedance.i.a.di;
import com.bytedance.i.a.dj;
import com.bytedance.i.a.dk;
import com.bytedance.i.a.dl;
import com.bytedance.i.a.dm;
import com.bytedance.i.a.dn;
import com.bytedance.i.a.dp;
import com.bytedance.i.a.dq;
import com.bytedance.i.a.dr;
import com.bytedance.i.a.ds;
import com.bytedance.i.a.dt;
import com.bytedance.i.a.du;
import com.bytedance.i.a.dv;
import com.bytedance.i.a.dw;
import com.bytedance.i.a.dx;
import com.bytedance.i.a.dy;
import com.bytedance.i.a.dz;
import com.bytedance.i.a.e;
import com.bytedance.i.a.ea;
import com.bytedance.i.a.eb;
import com.bytedance.i.a.ec;
import com.bytedance.i.a.ed;
import com.bytedance.i.a.ee;
import com.bytedance.i.a.ef;
import com.bytedance.i.a.eg;
import com.bytedance.i.a.eh;
import com.bytedance.i.a.ei;
import com.bytedance.i.a.ej;
import com.bytedance.i.a.ek;
import com.bytedance.i.a.el;
import com.bytedance.i.a.em;
import com.bytedance.i.a.en;
import com.bytedance.i.a.eo;
import com.bytedance.i.a.ep;
import com.bytedance.i.a.eq;
import com.bytedance.i.a.er;
import com.bytedance.i.a.es;
import com.bytedance.i.a.et;
import com.bytedance.i.a.eu;
import com.bytedance.i.a.ev;
import com.bytedance.i.a.ew;
import com.bytedance.i.a.ex;
import com.bytedance.i.a.ey;
import com.bytedance.i.a.ez;
import com.bytedance.i.a.f;
import com.bytedance.i.a.fa;
import com.bytedance.i.a.fb;
import com.bytedance.i.a.fc;
import com.bytedance.i.a.fd;
import com.bytedance.i.a.fe;
import com.bytedance.i.a.ff;
import com.bytedance.i.a.fg;
import com.bytedance.i.a.fh;
import com.bytedance.i.a.fi;
import com.bytedance.i.a.fj;
import com.bytedance.i.a.fk;
import com.bytedance.i.a.fl;
import com.bytedance.i.a.fm;
import com.bytedance.i.a.fn;
import com.bytedance.i.a.fo;
import com.bytedance.i.a.fp;
import com.bytedance.i.a.fq;
import com.bytedance.i.a.fr;
import com.bytedance.i.a.fs;
import com.bytedance.i.a.ft;
import com.bytedance.i.a.fu;
import com.bytedance.i.a.fv;
import com.bytedance.i.a.fw;
import com.bytedance.i.a.fx;
import com.bytedance.i.a.fy;
import com.bytedance.i.a.fz;
import com.bytedance.i.a.g;
import com.bytedance.i.a.ga;
import com.bytedance.i.a.gb;
import com.bytedance.i.a.gc;
import com.bytedance.i.a.gd;
import com.bytedance.i.a.ge;
import com.bytedance.i.a.gf;
import com.bytedance.i.a.gg;
import com.bytedance.i.a.gh;
import com.bytedance.i.a.gi;
import com.bytedance.i.a.gj;
import com.bytedance.i.a.gk;
import com.bytedance.i.a.gl;
import com.bytedance.i.a.gm;
import com.bytedance.i.a.gn;
import com.bytedance.i.a.go;
import com.bytedance.i.a.gp;
import com.bytedance.i.a.gq;
import com.bytedance.i.a.gr;
import com.bytedance.i.a.gs;
import com.bytedance.i.a.gt;
import com.bytedance.i.a.gu;
import com.bytedance.i.a.gv;
import com.bytedance.i.a.gw;
import com.bytedance.i.a.gx;
import com.bytedance.i.a.gy;
import com.bytedance.i.a.gz;
import com.bytedance.i.a.h;
import com.bytedance.i.a.ha;
import com.bytedance.i.a.hb;
import com.bytedance.i.a.hc;
import com.bytedance.i.a.hd;
import com.bytedance.i.a.he;
import com.bytedance.i.a.hf;
import com.bytedance.i.a.hg;
import com.bytedance.i.a.hh;
import com.bytedance.i.a.hi;
import com.bytedance.i.a.hj;
import com.bytedance.i.a.hk;
import com.bytedance.i.a.hl;
import com.bytedance.i.a.hm;
import com.bytedance.i.a.hn;
import com.bytedance.i.a.ho;
import com.bytedance.i.a.hp;
import com.bytedance.i.a.hq;
import com.bytedance.i.a.hr;
import com.bytedance.i.a.hs;
import com.bytedance.i.a.ht;
import com.bytedance.i.a.hu;
import com.bytedance.i.a.hv;
import com.bytedance.i.a.hw;
import com.bytedance.i.a.hx;
import com.bytedance.i.a.hy;
import com.bytedance.i.a.hz;
import com.bytedance.i.a.i;
import com.bytedance.i.a.ia;
import com.bytedance.i.a.ib;
import com.bytedance.i.a.ic;
import com.bytedance.i.a.id;
import com.bytedance.i.a.ie;
import com.bytedance.i.a.ig;
import com.bytedance.i.a.ih;
import com.bytedance.i.a.ii;
import com.bytedance.i.a.ij;
import com.bytedance.i.a.ik;
import com.bytedance.i.a.il;
import com.bytedance.i.a.im;
import com.bytedance.i.a.in;
import com.bytedance.i.a.io;
import com.bytedance.i.a.ip;
import com.bytedance.i.a.iq;
import com.bytedance.i.a.ir;
import com.bytedance.i.a.is;
import com.bytedance.i.a.it;
import com.bytedance.i.a.iu;
import com.bytedance.i.a.iv;
import com.bytedance.i.a.iw;
import com.bytedance.i.a.ix;
import com.bytedance.i.a.iy;
import com.bytedance.i.a.iz;
import com.bytedance.i.a.ja;
import com.bytedance.i.a.jb;
import com.bytedance.i.a.jc;
import com.bytedance.i.a.jd;
import com.bytedance.i.a.je;
import com.bytedance.i.a.jf;
import com.bytedance.i.a.jg;
import com.bytedance.i.a.jh;
import com.bytedance.i.a.ji;
import com.bytedance.i.a.jj;
import com.bytedance.i.a.jk;
import com.bytedance.i.a.jl;
import com.bytedance.i.a.jm;
import com.bytedance.i.a.jn;
import com.bytedance.i.a.jo;
import com.bytedance.i.a.jp;
import com.bytedance.i.a.jq;
import com.bytedance.i.a.jr;
import com.bytedance.i.a.js;
import com.bytedance.i.a.jt;
import com.bytedance.i.a.ju;
import com.bytedance.i.a.jv;
import com.bytedance.i.a.jw;
import com.bytedance.i.a.jx;
import com.bytedance.i.a.jy;
import com.bytedance.i.a.jz;
import com.bytedance.i.a.k;
import com.bytedance.i.a.ka;
import com.bytedance.i.a.kb;
import com.bytedance.i.a.kc;
import com.bytedance.i.a.kd;
import com.bytedance.i.a.ke;
import com.bytedance.i.a.kf;
import com.bytedance.i.a.kg;
import com.bytedance.i.a.kh;
import com.bytedance.i.a.ki;
import com.bytedance.i.a.kj;
import com.bytedance.i.a.kk;
import com.bytedance.i.a.kl;
import com.bytedance.i.a.km;
import com.bytedance.i.a.kn;
import com.bytedance.i.a.ko;
import com.bytedance.i.a.kp;
import com.bytedance.i.a.kq;
import com.bytedance.i.a.kr;
import com.bytedance.i.a.ks;
import com.bytedance.i.a.kt;
import com.bytedance.i.a.ku;
import com.bytedance.i.a.kv;
import com.bytedance.i.a.kw;
import com.bytedance.i.a.kx;
import com.bytedance.i.a.ky;
import com.bytedance.i.a.kz;
import com.bytedance.i.a.la;
import com.bytedance.i.a.lb;
import com.bytedance.i.a.lc;
import com.bytedance.i.a.ld;
import com.bytedance.i.a.le;
import com.bytedance.i.a.lf;
import com.bytedance.i.a.lg;
import com.bytedance.i.a.lh;
import com.bytedance.i.a.li;
import com.bytedance.i.a.lj;
import com.bytedance.i.a.lk;
import com.bytedance.i.a.ll;
import com.bytedance.i.a.lm;
import com.bytedance.i.a.ln;
import com.bytedance.i.a.lo;
import com.bytedance.i.a.lp;
import com.bytedance.i.a.lq;
import com.bytedance.i.a.lr;
import com.bytedance.i.a.ls;
import com.bytedance.i.a.lt;
import com.bytedance.i.a.lu;
import com.bytedance.i.a.lv;
import com.bytedance.i.a.lw;
import com.bytedance.i.a.lx;
import com.bytedance.i.a.ly;
import com.bytedance.i.a.lz;
import com.bytedance.i.a.ma;
import com.bytedance.i.a.mb;
import com.bytedance.i.a.mc;
import com.bytedance.i.a.md;
import com.bytedance.i.a.me;
import com.bytedance.i.a.mf;
import com.bytedance.i.a.mg;
import com.bytedance.i.a.mh;
import com.bytedance.i.a.mi;
import com.bytedance.i.a.mj;
import com.bytedance.i.a.mk;
import com.bytedance.i.a.ml;
import com.bytedance.i.a.mm;
import com.bytedance.i.a.mn;
import com.bytedance.i.a.mo;
import com.bytedance.i.a.mp;
import com.bytedance.i.a.mq;
import com.bytedance.i.a.mr;
import com.bytedance.i.a.ms;
import com.bytedance.i.a.mt;
import com.bytedance.i.a.mu;
import com.bytedance.i.a.mv;
import com.bytedance.i.a.mw;
import com.bytedance.i.a.mx;
import com.bytedance.i.a.my;
import com.bytedance.i.a.mz;
import com.bytedance.i.a.n;
import com.bytedance.i.a.na;
import com.bytedance.i.a.nb;
import com.bytedance.i.a.nc;
import com.bytedance.i.a.nd;
import com.bytedance.i.a.ne;
import com.bytedance.i.a.nf;
import com.bytedance.i.a.ng;
import com.bytedance.i.a.nh;
import com.bytedance.i.a.ni;
import com.bytedance.i.a.nj;
import com.bytedance.i.a.nk;
import com.bytedance.i.a.nl;
import com.bytedance.i.a.nm;
import com.bytedance.i.a.nn;
import com.bytedance.i.a.no;
import com.bytedance.i.a.np;
import com.bytedance.i.a.nq;
import com.bytedance.i.a.nr;
import com.bytedance.i.a.ns;
import com.bytedance.i.a.nt;
import com.bytedance.i.a.nu;
import com.bytedance.i.a.nv;
import com.bytedance.i.a.nw;
import com.bytedance.i.a.nx;
import com.bytedance.i.a.ny;
import com.bytedance.i.a.nz;
import com.bytedance.i.a.o;
import com.bytedance.i.a.oa;
import com.bytedance.i.a.ob;
import com.bytedance.i.a.oc;
import com.bytedance.i.a.od;
import com.bytedance.i.a.oe;
import com.bytedance.i.a.of;
import com.bytedance.i.a.og;
import com.bytedance.i.a.oh;
import com.bytedance.i.a.oi;
import com.bytedance.i.a.oj;
import com.bytedance.i.a.ok;
import com.bytedance.i.a.ol;
import com.bytedance.i.a.om;
import com.bytedance.i.a.on;
import com.bytedance.i.a.oo;
import com.bytedance.i.a.op;
import com.bytedance.i.a.oq;
import com.bytedance.i.a.or;
import com.bytedance.i.a.os;
import com.bytedance.i.a.ot;
import com.bytedance.i.a.ou;
import com.bytedance.i.a.ov;
import com.bytedance.i.a.ow;
import com.bytedance.i.a.ox;
import com.bytedance.i.a.oy;
import com.bytedance.i.a.oz;
import com.bytedance.i.a.p;
import com.bytedance.i.a.pa;
import com.bytedance.i.a.pb;
import com.bytedance.i.a.pc;
import com.bytedance.i.a.pd;
import com.bytedance.i.a.pe;
import com.bytedance.i.a.pf;
import com.bytedance.i.a.pg;
import com.bytedance.i.a.ph;
import com.bytedance.i.a.pi;
import com.bytedance.i.a.pj;
import com.bytedance.i.a.pk;
import com.bytedance.i.a.pl;
import com.bytedance.i.a.pm;
import com.bytedance.i.a.pn;
import com.bytedance.i.a.po;
import com.bytedance.i.a.pp;
import com.bytedance.i.a.pq;
import com.bytedance.i.a.pr;
import com.bytedance.i.a.ps;
import com.bytedance.i.a.pt;
import com.bytedance.i.a.pu;
import com.bytedance.i.a.pv;
import com.bytedance.i.a.pw;
import com.bytedance.i.a.px;
import com.bytedance.i.a.py;
import com.bytedance.i.a.pz;
import com.bytedance.i.a.q;
import com.bytedance.i.a.r;
import com.bytedance.i.a.s;
import com.bytedance.i.a.t;
import com.bytedance.i.a.u;
import com.bytedance.i.a.v;
import com.bytedance.i.a.w;
import com.bytedance.i.a.x;
import com.bytedance.i.a.y;
import com.bytedance.tux.b.j;
import com.zhiliaoapp.musically.R;
import h.f.a.b;
import h.f.b.aa;
import h.f.b.l;
import h.f.b.m;
import h.z;

public final class a {
    static {
        Covode.recordClassIndex(92450);
    }

    /* renamed from: com.ss.android.ugc.aweme.tux.a.d.a$a  reason: collision with other inner class name */
    public static final class C3756a extends m implements b<j, z> {

        /* renamed from: a  reason: collision with root package name */
        public static final C3756a f141525a = new C3756a();

        static {
            Covode.recordClassIndex(92451);
        }

        C3756a() {
            super(1);
        }

        /* Return type fixed from 'java.lang.Object' to match base method */
        /* JADX DEBUG: Method arguments types fixed to match base method, original types: [java.lang.Object] */
        @Override // h.f.a.b
        public final /* synthetic */ z invoke(j jVar) {
            a(jVar);
            return z.f158842a;
        }

        private static void a(j jVar) {
            l.d(jVar, "");
            j.a(jVar, R.raw.icon_large_unavailable_region, aa.a(ki.class), false, 4);
            j.a(jVar, R.raw.icon_large_direct_message, aa.a(jg.class), false, 4);
            j.a(jVar, R.raw.icon_large_tiktok_logo, aa.a(kh.class), false, 4);
            j.a(jVar, R.raw.icon_large_inbox, aa.a(jp.class), false, 4);
            j.a(jVar, R.raw.icon_large_music_note, aa.a(ju.class), false, 4);
            j.a(jVar, R.raw.icon_large_magnify_glass, aa.a(js.class), false, 4);
            j.a(jVar, R.raw.icon_large_404, aa.a(ja.class), false, 4);
            j.a(jVar, R.raw.icon_large_private_account, aa.a(kc.class), false, 4);
            j.a(jVar, R.raw.icon_large_protection, aa.a(kd.class), false, 4);
            j.a(jVar, R.raw.icon_large_live_wallpaper, aa.a(jq.class), false, 4);
            j.a(jVar, R.raw.icon_large_person, aa.a(ka.class), false, 4);
            j.a(jVar, R.raw.icon_large_follow_request, aa.a(jl.class), false, 4);
            j.a(jVar, R.raw.icon_large_paperplane_mailbox, aa.a(jz.class), false, 4);
            j.a(jVar, R.raw.icon_large_folder_arrow_down, aa.a(jk.class), false, 4);
            j.a(jVar, R.raw.icon_large_error_qa, aa.a(ji.class), false, 4);
            j.a(jVar, R.raw.icon_large_calendar_star, aa.a(je.class), false, 4);
            j.a(jVar, R.raw.icon_large_no_video, aa.a(jw.class), false, 4);
            j.a(jVar, R.raw.icon_large_group, aa.a(jm.class), false, 4);
            j.a(jVar, R.raw.icon_large_effect, aa.a(jh.class), false, 4);
            j.a(jVar, R.raw.icon_large_store, aa.a(kf.class), false, 4);
            j.a(jVar, R.raw.icon_large_not_started, aa.a(jx.class), false, 4);
            j.a(jVar, R.raw.icon_large_lock, aa.a(jr.class), false, 4);
            j.a(jVar, R.raw.icon_large_error_robot, aa.a(jj.class), false, 4);
            j.a(jVar, R.raw.icon_large_hashtag, aa.a(jn.class), false, 4);
            j.a(jVar, R.raw.icon_large_refresh, aa.a(ke.class), false, 4);
            j.a(jVar, R.raw.icon_large_bookmark, aa.a(jd.class), false, 4);
            j.a(jVar, R.raw.icon_large_heart, aa.a(jo.class), false, 4);
            j.a(jVar, R.raw.icon_large_story_camera, aa.a(kg.class), false, 4);
            j.a(jVar, R.raw.icon_large_wifi_slash, aa.a(kk.class), false, 4);
            j.a(jVar, R.raw.icon_large_photo, aa.a(kb.class), false, 4);
            j.a(jVar, R.raw.icon_large_bag, aa.a(jc.class), false, 4);
            j.a(jVar, R.raw.icon_large_missed_event, aa.a(jt.class), false, 4);
            j.a(jVar, R.raw.icon_large_video, aa.a(kj.class), false, 4);
            j.a(jVar, R.raw.icon_large_no_access, aa.a(jv.class), false, 4);
            j.a(jVar, R.raw.icon_large_comment, aa.a(jf.class), false, 4);
            j.a(jVar, R.raw.icon_large_at_mention, aa.a(jb.class), false, 4);
            j.a(jVar, R.raw.icon_large_overloaded_server, aa.a(jy.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_donation, aa.a(ci.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_miniprogram, aa.a(cq.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_resso, aa.a(ct.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_game, aa.a(cm.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_map_pin, aa.a(cp.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_tripadvisor, aa.a(cx.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_event, aa.a(ck.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_yelp, aa.a(da.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_imdb, aa.a(co.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_effect, aa.a(cj.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_wikipedia, aa.a(cz.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_film, aa.a(cl.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_green_screen, aa.a(cn.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_viamaker, aa.a(cy.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_photo_motion, aa.a(cr.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_product, aa.a(cs.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_stitch, aa.a(cu.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_templates, aa.a(cv.class), false, 4);
            j.a(jVar, R.raw.icon_anchor_tiktok_shoutouts, aa.a(cw.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_line_circle, aa.a(s.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_envelope, aa.a(com.bytedance.i.a.m.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_music_note, aa.a(com.bytedance.i.a.z.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_line_chart, aa.a(r.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_person_lock, aa.a(ac.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_person_x_mark, aa.a(ae.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_mask, aa.a(y.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_effect, aa.a(com.bytedance.i.a.l.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_trash_bin, aa.a(ao.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_playlist, aa.a(ah.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_playlist_fill, aa.a(ai.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_live_photo, aa.a(u.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_block, aa.a(c.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_arrow_to_bottom, aa.a(com.bytedance.i.a.b.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_live_wallpaper, aa.a(v.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_number, aa.a(com.bytedance.i.a.aa.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_qrcode, aa.a(aj.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_duet, aa.a(k.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_arrow_stroke_to_top, aa.a(com.bytedance.i.a.a.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_react, aa.a(al.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_pin, aa.a(af.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_compass, aa.a(com.bytedance.i.a.j.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_shopping_bag_star, null, false, 6);
            j.a(jVar, R.raw.icon_2pt_video, null, false, 6);
            jVar.a(R.raw.icon_2pt_horn_ltr, aa.a(q.class), true);
            j.a(jVar, R.raw.icon_2pt_gif, aa.a(p.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_bookmark, aa.a(e.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_stitch, aa.a(am.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_pin_fill, aa.a(ag.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_bookmark_fill, aa.a(f.class), false, 4);
            jVar.a(R.raw.icon_2pt_question_mark_circle_ltr, aa.a(ak.class), true);
            j.a(jVar, R.raw.icon_2pt_broken_heart, aa.a(g.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_link, aa.a(t.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_magnifying_glass, aa.a(x.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_lock, aa.a(w.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_fire, aa.a(n.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_calendar_tick, aa.a(i.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_flag, aa.a(o.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_pen_on_doc, aa.a(ab.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_book, aa.a(d.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_video_edit, aa.a(ap.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_person_monitor, aa.a(ad.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_bubble_ellipsis_right, aa.a(h.class), false, 4);
            j.a(jVar, R.raw.icon_2pt_template, aa.a(an.class), false, 4);
            j.a(jVar, R.raw.icon_color_gradient_heart, aa.a(fz.class), false, 4);
            j.a(jVar, R.raw.icon_color_pinterest, aa.a(gg.class), false, 4);
            j.a(jVar, R.raw.icon_color_ellipsis_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_telegram_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_instagram_story_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_slack_circle, aa.a(gj.class), false, 4);
            j.a(jVar, R.raw.icon_color_tiktok_coin, aa.a(gk.class), false, 4);
            j.a(jVar, R.raw.icon_color_download_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_whatsapp_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_facebook, null, false, 6);
            j.a(jVar, R.raw.icon_color_vk_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_contact_circle, aa.a(fs.class), false, 4);
            j.a(jVar, R.raw.icon_color_kakaostory_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_viber_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_line_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_fire_circle, aa.a(fw.class), false, 4);
            j.a(jVar, R.raw.icon_color_comment_shadow, null, false, 6);
            j.a(jVar, R.raw.icon_color_email_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_youtube_circle, aa.a(gr.class), false, 4);
            j.a(jVar, R.raw.icon_color_like_circle, aa.a(gd.class), false, 4);
            j.a(jVar, R.raw.icon_color_sms_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_vk, aa.a(gq.class), false, 4);
            j.a(jVar, R.raw.icon_color_twitter, aa.a(gn.class), false, 4);
            j.a(jVar, R.raw.icon_color_band_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_line, aa.a(ge.class), false, 4);
            j.a(jVar, R.raw.icon_color_plus_circle_live, null, false, 6);
            j.a(jVar, R.raw.icon_color_google, aa.a(fy.class), false, 4);
            j.a(jVar, R.raw.icon_color_share_shadow, null, false, 6);
            j.a(jVar, R.raw.icon_color_messenger_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_messenger_lite_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_naverblog_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_navercafe_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_twitter_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_kakaotalk_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_default_avatar, aa.a(fv.class), false, 4);
            j.a(jVar, R.raw.icon_color_imgur_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_link_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_phone_circle, aa.a(gf.class), false, 4);
            j.a(jVar, R.raw.icon_color_like_red_shadow, null, false, 6);
            j.a(jVar, R.raw.icon_color_play, null, false, 6);
            j.a(jVar, R.raw.icon_color_reddit_circle, aa.a(gh.class), false, 4);
            j.a(jVar, R.raw.icon_color_view_circle, aa.a(gp.class), false, 4);
            j.a(jVar, R.raw.icon_color_ellipsis_shadow, null, false, 6);
            j.a(jVar, R.raw.icon_color_qr_code_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_snapchat_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_zalo_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_anchors, aa.a(fo.class), false, 4);
            j.a(jVar, R.raw.icon_color_kakaotalk, aa.a(gc.class), false, 4);
            j.a(jVar, R.raw.icon_color_create_dark, aa.a(ft.class), false, 4);
            j.a(jVar, R.raw.icon_color_direct_message_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_chrome, aa.a(fr.class), false, 4);
            j.a(jVar, R.raw.icon_color_tiktok_logo_light, aa.a(gm.class), false, 4);
            j.a(jVar, R.raw.icon_color_like_shadow, null, false, 6);
            j.a(jVar, R.raw.icon_color_pause, null, false, 6);
            j.a(jVar, R.raw.icon_color_verified_badge, aa.a(go.class), false, 4);
            j.a(jVar, R.raw.icon_color_artist, aa.a(fq.class), false, 4);
            j.a(jVar, R.raw.icon_color_instagram, aa.a(ga.class), false, 4);
            j.a(jVar, R.raw.icon_color_rewards, aa.a(gi.class), false, 4);
            j.a(jVar, R.raw.icon_color_gift, aa.a(fx.class), false, 4);
            j.a(jVar, R.raw.icon_color_instagram_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_create_light, aa.a(fu.class), false, 4);
            j.a(jVar, R.raw.icon_color_facebook_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_apple, aa.a(fp.class), false, 4);
            j.a(jVar, R.raw.icon_color_invitation_circle, aa.a(gb.class), false, 4);
            j.a(jVar, R.raw.icon_color_facebook_lite_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_tiktok_logo_dark, aa.a(gl.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_magnifying_glass_rectangle, aa.a(bs.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_collection, aa.a(bb.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_cloud_arrow_up_fill, aa.a(ba.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_private_account, aa.a(by.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_bag, aa.a(av.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_backspace, aa.a(au.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_tiktok_logo, aa.a(cd.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_keyboard, aa.a(bo.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_effect, aa.a(bg.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_dm_emoji, aa.a(bd.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_plus_circle, aa.a(bx.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_bell, aa.a(aw.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_music_note, aa.a(bt.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_number, aa.a(bv.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_3_lines_horizontal, aa.a(as.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_refresh, aa.a(ca.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_store, aa.a(cb.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_paperplane, aa.a(bw.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_link, aa.a(bp.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_fire, aa.a(bi.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_lock, aa.a(br.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_heart_eye_slash, aa.a(bl.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_live_photo, aa.a(bq.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_video_slash, aa.a(cf.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_camera, aa.a(ay.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_image, aa.a(bn.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_navi, aa.a(bu.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_bubble_ellipsis_right, aa.a(ax.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_diamond_stroke, aa.a(bc.class), false, 4);
            jVar.a(R.raw.icon_3pt_horn_ltr, aa.a(bm.class), true);
            j.a(jVar, R.raw.icon_3pt_dollar_sign, aa.a(be.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_closed_caption, aa.a(az.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_template, aa.a(cc.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_arrow_turn_up_right, aa.a(at.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_react, aa.a(bz.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_video, aa.a(ce.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_duet, aa.a(bf.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_heart, aa.a(bk.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_gif, aa.a(bj.class), false, 4);
            j.a(jVar, R.raw.icon_3pt_exclamation_mark_circle, aa.a(bh.class), false, 4);
            j.a(jVar, R.raw.icon_ellipsis_horizontal, aa.a(hg.class), false, 4);
            j.a(jVar, R.raw.icon_at_fill, aa.a(dw.class), false, 4);
            j.a(jVar, R.raw.icon_family, aa.a(hs.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_left_right_circle, aa.a(dg.class), false, 4);
            j.a(jVar, R.raw.icon_gif_rectangle, aa.a(ii.class), false, 4);
            j.a(jVar, R.raw.icon_playlist, aa.a(mj.class), false, 4);
            j.a(jVar, R.raw.icon_plus_small, aa.a(mm.class), false, 4);
            j.a(jVar, R.raw.icon_flashlight_fill, aa.a(ib.class), false, 4);
            j.a(jVar, R.raw.icon_person_tick, aa.a(mb.class), false, 4);
            j.a(jVar, R.raw.icon_tick_circle, aa.a(ov.class), false, 4);
            j.a(jVar, R.raw.icon_effect, aa.a(hf.class), false, 4);
            j.a(jVar, R.raw.icon_tick_fill, aa.a(ox.class), false, 4);
            j.a(jVar, R.raw.icon_draft, aa.a(hb.class), false, 4);
            j.a(jVar, R.raw.icon_person_plus, aa.a(ly.class), false, 4);
            j.a(jVar, R.raw.icon_qr_code, aa.a(mr.class), false, 4);
            j.a(jVar, R.raw.icon_info_circle, aa.a(ix.class), false, 4);
            j.a(jVar, R.raw.icon_play_small, aa.a(mi.class), false, 4);
            j.a(jVar, R.raw.icon_copyright, aa.a(gt.class), false, 4);
            j.a(jVar, R.raw.icon_misc_fill, aa.a(lh.class), false, 4);
            j.a(jVar, R.raw.icon_closed_caption, aa.a(fn.class), false, 4);
            j.a(jVar, R.raw.icon_paperplane_fill, aa.a(ln.class), false, 4);
            j.a(jVar, R.raw.icon_hourglass, aa.a(iw.class), false, 4);
            j.a(jVar, R.raw.icon_sun, aa.a(nx.class), false, 4);
            j.a(jVar, R.raw.icon_bubble_ellipsis_right, aa.a(eo.class), false, 4);
            j.a(jVar, R.raw.icon_star, aa.a(no.class), false, 4);
            j.a(jVar, R.raw.icon_flip_camera, aa.a(ic.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_left_right, aa.a(df.class), false, 4);
            j.a(jVar, R.raw.icon_person_circle, aa.a(lw.class), false, 4);
            j.a(jVar, R.raw.icon_spinner_normal, aa.a(nm.class), false, 4);
            j.a(jVar, R.raw.icon_calendar_star, aa.a(ev.class), false, 4);
            j.a(jVar, R.raw.icon_document, aa.a(gy.class), false, 4);
            j.a(jVar, R.raw.icon_bell_activation, aa.a(ed.class), false, 4);
            j.a(jVar, R.raw.icon_bubble_left_right, aa.a(er.class), false, 4);
            j.a(jVar, R.raw.icon_line_chart_fill, aa.a(kn.class), false, 4);
            j.a(jVar, R.raw.icon_double_circle, aa.a(ha.class), false, 4);
            j.a(jVar, R.raw.icon_video_fill, aa.a(pn.class), false, 4);
            j.a(jVar, R.raw.icon_play, aa.a(mg.class), false, 4);
            j.a(jVar, R.raw.icon_pause_fill, aa.a(lo.class), false, 4);
            j.a(jVar, R.raw.icon_full_screen, aa.a(Cif.class), false, 4);
            j.a(jVar, R.raw.icon_film_star, aa.a(hv.class), false, 4);
            j.a(jVar, R.raw.icon_shield_plus, aa.a(na.class), false, 4);
            j.a(jVar, R.raw.icon_shopping_bag_star, aa.a(nd.class), false, 4);
            j.a(jVar, R.raw.icon_misc, aa.a(lg.class), false, 4);
            j.a(jVar, R.raw.icon_auto_language, aa.a(dx.class), false, 4);
            jVar.a(R.raw.icon_chevron_right_offset_fill_ltr, aa.a(fg.class), true);
            j.a(jVar, R.raw.icon_chevron_down_small_fill, aa.a(fc.class), false, 4);
            jVar.a(R.raw.icon_truck_moving_fill_ltr, aa.a(pf.class), true);
            j.a(jVar, R.raw.icon_instagram, null, false, 6);
            j.a(jVar, R.raw.icon_instagram_story, null, false, 6);
            j.a(jVar, R.raw.icon_whatsapp, null, false, 6);
            j.a(jVar, R.raw.icon_facebook, null, false, 6);
            j.a(jVar, R.raw.icon_messages, null, false, 6);
            j.a(jVar, R.raw.icon_messenger, null, false, 6);
            j.a(jVar, R.raw.icon_vk, null, false, 6);
            j.a(jVar, R.raw.icon_snapchat, null, false, 6);
            j.a(jVar, R.raw.icon_line, null, false, 6);
            j.a(jVar, R.raw.icon_zalo, null, false, 6);
            j.a(jVar, R.raw.icon_kakaotalk, null, false, 6);
            j.a(jVar, R.raw.icon_twitter, null, false, 6);
            j.a(jVar, R.raw.icon_x_mark_circle_fill, aa.a(pw.class), false, 4);
            j.a(jVar, R.raw.icon_thumbs_up, aa.a(os.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_triangle_down_fill, aa.a(dm.class), false, 4);
            j.a(jVar, R.raw.icon_lock_fill, aa.a(kw.class), false, 4);
            j.a(jVar, R.raw.icon_bag, aa.a(dz.class), false, 4);
            j.a(jVar, R.raw.icon_tiktok_logo, aa.a(oz.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_turn_up_left, aa.a(dp.class), false, 4);
            j.a(jVar, R.raw.icon_shield_tick, aa.a(nb.class), false, 4);
            j.a(jVar, R.raw.icon_two_person_fill, aa.a(pi.class), false, 4);
            j.a(jVar, R.raw.icon_playlist_fill, aa.a(mk.class), false, 4);
            j.a(jVar, R.raw.icon_navi, aa.a(lk.class), false, 4);
            j.a(jVar, R.raw.icon_heart_small, aa.a(iu.class), false, 4);
            j.a(jVar, R.raw.icon_x_mark, aa.a(pv.class), false, 4);
            j.a(jVar, R.raw.icon_3_lines_horizontal, aa.a(aq.class), false, 4);
            j.a(jVar, R.raw.icon_two_person, aa.a(ph.class), false, 4);
            j.a(jVar, R.raw.icon_coupon_fill, aa.a(gv.class), false, 4);
            j.a(jVar, R.raw.icon_person, aa.a(lt.class), false, 4);
            j.a(jVar, R.raw.icon_location_north, aa.a(ku.class), false, 4);
            j.a(jVar, R.raw.icon_scan, aa.a(my.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_to_left, aa.a(dk.class), false, 4);
            j.a(jVar, R.raw.icon_envelope, aa.a(hj.class), false, 4);
            j.a(jVar, R.raw.icon_bell_fill, aa.a(ee.class), false, 4);
            j.a(jVar, R.raw.icon_chevron_down_fill, aa.a(fb.class), false, 4);
            j.a(jVar, R.raw.icon_phone_video, aa.a(md.class), false, 4);
            j.a(jVar, R.raw.icon_instagram, aa.a(iy.class), false, 4);
            j.a(jVar, R.raw.icon_wallet, aa.a(pr.class), false, 4);
            j.a(jVar, R.raw.icon_react, aa.a(mt.class), false, 4);
            j.a(jVar, R.raw.icon_video, aa.a(pm.class), false, 4);
            j.a(jVar, R.raw.icon_exclamation_mark_circle, aa.a(hl.class), false, 4);
            j.a(jVar, R.raw.icon_file_tick, aa.a(hu.class), false, 4);
            j.a(jVar, R.raw.icon_moon, aa.a(li.class), false, 4);
            j.a(jVar, R.raw.icon_tiktok_logo_circle, aa.a(pa.class), false, 4);
            j.a(jVar, R.raw.icon_exclamation_mark, aa.a(hk.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_up_right_and_arrow_down_left, aa.a(dt.class), false, 4);
            j.a(jVar, R.raw.icon_globe, aa.a(ik.class), false, 4);
            jVar.a(R.raw.icon_arrow_triangle_right_fill_ltr, aa.a(Cdo.class), true);
            j.a(jVar, R.raw.icon_doc_on_doc, aa.a(gx.class), false, 4);
            j.a(jVar, R.raw.icon_private_account, aa.a(mo.class), false, 4);
            j.a(jVar, R.raw.icon_duet, aa.a(hd.class), false, 4);
            j.a(jVar, R.raw.icon_phone, aa.a(mc.class), false, 4);
            j.a(jVar, R.raw.icon_clock, aa.a(fm.class), false, 4);
            j.a(jVar, R.raw.icon_store_fill, aa.a(nt.class), false, 4);
            j.a(jVar, R.raw.icon_spinner_thin, aa.a(nn.class), false, 4);
            j.a(jVar, R.raw.icon_microphone, aa.a(lc.class), false, 4);
            j.a(jVar, R.raw.icon_replay, aa.a(mw.class), false, 4);
            j.a(jVar, R.raw.icon_star_map, aa.a(nq.class), false, 4);
            j.a(jVar, R.raw.icon_eye_close, aa.a(hp.class), false, 4);
            jVar.a(R.raw.icon_clipboard_ltr, aa.a(fl.class), true);
            j.a(jVar, R.raw.icon_ear, aa.a(he.class), false, 4);
            j.a(jVar, R.raw.icon_fire_2_fill, aa.a(hy.class), false, 4);
            j.a(jVar, R.raw.icon_keyboard_circle, aa.a(iz.class), false, 4);
            j.a(jVar, R.raw.icon_magnifying_glass_rectangle, aa.a(la.class), false, 4);
            j.a(jVar, R.raw.icon_minus, aa.a(lf.class), false, 4);
            j.a(jVar, R.raw.icon_heart_fill, aa.a(it.class), false, 4);
            j.a(jVar, R.raw.icon_thumbs_up_fill, aa.a(ot.class), false, 4);
            j.a(jVar, R.raw.icon_story_camera_fill, aa.a(nv.class), false, 4);
            j.a(jVar, R.raw.icon_tips, aa.a(pd.class), false, 4);
            j.a(jVar, R.raw.icon_repeat_1, aa.a(mv.class), false, 4);
            j.a(jVar, R.raw.icon_block, aa.a(eg.class), false, 4);
            j.a(jVar, R.raw.icon_shopping_cart, aa.a(ne.class), false, 4);
            j.a(jVar, R.raw.icon_heart, aa.a(iq.class), false, 4);
            jVar.a(R.raw.icon_qa_ltr, aa.a(mp.class), true);
            j.a(jVar, R.raw.icon_beaker, aa.a(eb.class), false, 4);
            j.a(jVar, R.raw.icon_video_slash, aa.a(pp.class), false, 4);
            j.a(jVar, R.raw.icon_pen_on_doc, aa.a(lr.class), false, 4);
            j.a(jVar, R.raw.icon_play_fill, aa.a(mh.class), false, 4);
            jVar.a(R.raw.icon_person_question_mark_ltr, aa.a(lz.class), true);
            j.a(jVar, R.raw.icon_box_uturn_left, aa.a(em.class), false, 4);
            j.a(jVar, R.raw.icon_drop_bolt, aa.a(hc.class), false, 4);
            j.a(jVar, R.raw.icon_flashlight, aa.a(ia.class), false, 4);
            j.a(jVar, R.raw.icon_pause_fill1, aa.a(lp.class), false, 4);
            j.a(jVar, R.raw.icon_person_arrow_left_right_fill, aa.a(lv.class), false, 4);
            j.a(jVar, R.raw.icon_umbrella, aa.a(pj.class), false, 4);
            j.a(jVar, R.raw.icon_bolt_fill, aa.a(eh.class), false, 4);
            j.a(jVar, R.raw.icon_number, aa.a(ll.class), false, 4);
            j.a(jVar, R.raw.icon_map_pin, aa.a(lb.class), false, 4);
            j.a(jVar, R.raw.icon_headphone_slash, aa.a(io.class), false, 4);
            j.a(jVar, R.raw.icon_timer_lock, aa.a(pc.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_up_line_fill, aa.a(ds.class), false, 4);
            j.a(jVar, R.raw.icon_lines_horizontal_decrease, aa.a(ko.class), false, 4);
            j.a(jVar, R.raw.icon_eye, aa.a(ho.class), false, 4);
            j.a(jVar, R.raw.icon_gift, aa.a(ij.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_down_cloud, aa.a(db.class), false, 4);
            j.a(jVar, R.raw.icon_bubble_line_fill, aa.a(es.class), false, 4);
            j.a(jVar, R.raw.icon_line_chart, aa.a(km.class), false, 4);
            j.a(jVar, R.raw.icon_story_star, aa.a(nw.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_to_right, aa.a(dl.class), false, 4);
            j.a(jVar, R.raw.icon_chevron_down_double_fill, aa.a(fa.class), false, 4);
            j.a(jVar, R.raw.icon_a_rectangle, aa.a(cg.class), false, 4);
            j.a(jVar, R.raw.icon_3_lines_horizontal_2, aa.a(ar.class), false, 4);
            j.a(jVar, R.raw.icon_pin_fill, aa.a(mf.class), false, 4);
            j.a(jVar, R.raw.icon_resso, aa.a(mx.class), false, 4);
            j.a(jVar, R.raw.icon_cell_site, aa.a(ey.class), false, 4);
            j.a(jVar, R.raw.icon_music_note, aa.a(lj.class), false, 4);
            j.a(jVar, R.raw.icon_bookmark, aa.a(ek.class), false, 4);
            j.a(jVar, R.raw.icon_person_fill, aa.a(lx.class), false, 4);
            jVar.a(R.raw.icon_speaker_2_ltr, aa.a(ni.class), true);
            j.a(jVar, R.raw.icon_video_split, aa.a(pq.class), false, 4);
            j.a(jVar, R.raw.icon_tick_fill_small, aa.a(oy.class), false, 4);
            j.a(jVar, R.raw.icon_vertical_bars, aa.a(pl.class), false, 4);
            j.a(jVar, R.raw.icon_red_envelope, aa.a(mu.class), false, 4);
            j.a(jVar, R.raw.icon_unlock, aa.a(pk.class), false, 4);
            j.a(jVar, R.raw.icon_bell_slash, aa.a(ef.class), false, 4);
            j.a(jVar, R.raw.icon_paperplane, aa.a(lm.class), false, 4);
            j.a(jVar, R.raw.icon_tilt_light_bulb, aa.a(pb.class), false, 4);
            j.a(jVar, R.raw.icon_lock_small, aa.a(kx.class), false, 4);
            j.a(jVar, R.raw.icon_go_live_together, aa.a(il.class), false, 4);
            j.a(jVar, R.raw.icon_dollar_sign, aa.a(gz.class), false, 4);
            j.a(jVar, R.raw.icon_live_wallpaper, aa.a(kt.class), false, 4);
            j.a(jVar, R.raw.icon_stitch, aa.a(nr.class), false, 4);
            jVar.a(R.raw.icon_chevron_left_offset_ltr, aa.a(fe.class), true);
            jVar.a(R.raw.icon_chevron_left_ltr, aa.a(fd.class), true);
            j.a(jVar, R.raw.icon_ellipsis_vertical, aa.a(hh.class), false, 4);
            jVar.a(R.raw.icon_arrow_up_left_ltr, aa.a(dr.class), true);
            jVar.a(R.raw.icon_horn_ltr, aa.a(iv.class), true);
            j.a(jVar, R.raw.icon_x_mark_fill_small, aa.a(px.class), false, 4);
            jVar.a(R.raw.icon_arrow_right_ltr, aa.a(di.class), true);
            j.a(jVar, R.raw.icon_scope, aa.a(mz.class), false, 4);
            j.a(jVar, R.raw.icon_eye_fill, aa.a(hq.class), false, 4);
            j.a(jVar, R.raw.icon_bookmark_fill, aa.a(el.class), false, 4);
            j.a(jVar, R.raw.icon_microphone_slash, aa.a(ld.class), false, 4);
            j.a(jVar, R.raw.icon_bank_card, aa.a(ea.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_turn_up_right, aa.a(dq.class), false, 4);
            j.a(jVar, R.raw.icon_magnifying_glass, aa.a(kz.class), false, 4);
            j.a(jVar, R.raw.icon_light_bulb_fill, aa.a(kl.class), false, 4);
            j.a(jVar, R.raw.icon_live_photo, aa.a(ks.class), false, 4);
            j.a(jVar, R.raw.icon_person_arrow_left_right, aa.a(lu.class), false, 4);
            j.a(jVar, R.raw.icon_trash_bin, aa.a(pe.class), false, 4);
            j.a(jVar, R.raw.icon_camera, aa.a(ex.class), false, 4);
            jVar.a(R.raw.icon_arrow_left_circle_ltr, aa.a(dd.class), true);
            j.a(jVar, R.raw.icon_calendar, aa.a(eu.class), false, 4);
            j.a(jVar, R.raw.icon_story_camera, aa.a(nu.class), false, 4);
            j.a(jVar, R.raw.icon_folder_arrow_down, aa.a(ie.class), false, 4);
            j.a(jVar, R.raw.icon_eye_slash, aa.a(hr.class), false, 4);
            j.a(jVar, R.raw.icon_heart_broken, aa.a(ir.class), false, 4);
            j.a(jVar, R.raw.icon_coupon, aa.a(gu.class), false, 4);
            j.a(jVar, R.raw.icon_exclamation_mark_circle_fill, aa.a(hm.class), false, 4);
            j.a(jVar, R.raw.icon_pen_on_paper, aa.a(ls.class), false, 4);
            j.a(jVar, R.raw.icon_hd_rectangle, aa.a(im.class), false, 4);
            j.a(jVar, R.raw.icon_headphone, aa.a(in.class), false, 4);
            jVar.a(R.raw.icon_arrow_left_ltr, aa.a(de.class), true);
            j.a(jVar, R.raw.icon_at, aa.a(dv.class), false, 4);
            j.a(jVar, R.raw.icon_wallet_add, aa.a(ps.class), false, 4);
            j.a(jVar, R.raw.icon_plus, aa.a(ml.class), false, 4);
            j.a(jVar, R.raw.icon_template, aa.a(or.class), false, 4);
            jVar.a(R.raw.icon_qa_fill_ltr, aa.a(mq.class), true);
            jVar.a(R.raw.icon_truck_moving_ltr, aa.a(pg.class), true);
            jVar.a(R.raw.icon_bubble_left_ltr, aa.a(eq.class), true);
            j.a(jVar, R.raw.icon_person_star, aa.a(ma.class), false, 4);
            j.a(jVar, R.raw.icon_wifi, aa.a(pu.class), false, 4);
            j.a(jVar, R.raw.icon_gear, aa.a(ig.class), false, 4);
            j.a(jVar, R.raw.icon_chevron_up_fill, aa.a(fk.class), false, 4);
            j.a(jVar, R.raw.icon_shoutouts, aa.a(nf.class), false, 4);
            j.a(jVar, R.raw.icon_list_arrow_down, aa.a(kr.class), false, 4);
            j.a(jVar, R.raw.icon_emoji, aa.a(hi.class), false, 4);
            j.a(jVar, R.raw.icon_exclamation_mark_triangle_fill, aa.a(hn.class), false, 4);
            jVar.a(R.raw.icon_speaker_x_mark_fill_ltr, aa.a(nk.class), true);
            j.a(jVar, R.raw.icon_arrow_triangle_down_large_fill, aa.a(dn.class), false, 4);
            jVar.a(R.raw.icon_question_mark_circle_ltr, aa.a(ms.class), true);
            j.a(jVar, R.raw.icon_folder, aa.a(id.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_down_to_line, aa.a(dc.class), false, 4);
            j.a(jVar, R.raw.icon_tick_cirlce_fill, aa.a(ow.class), false, 4);
            j.a(jVar, R.raw.icon_star_fill, aa.a(np.class), false, 4);
            j.a(jVar, R.raw.icon_book, aa.a(ei.class), false, 4);
            jVar.a(R.raw.icon_chevron_right_offset_ltr, aa.a(fh.class), true);
            j.a(jVar, R.raw.icon_miniprogram, aa.a(le.class), false, 4);
            j.a(jVar, R.raw.icon_bell, aa.a(ec.class), false, 4);
            j.a(jVar, R.raw.icon_heart_circle_loop, aa.a(is.class), false, 4);
            j.a(jVar, R.raw.icon_tick, aa.a(ou.class), false, 4);
            j.a(jVar, R.raw.icon_store, aa.a(ns.class), false, 4);
            j.a(jVar, R.raw.icon_bubble_ellipsis_right_fill, aa.a(ep.class), false, 4);
            j.a(jVar, R.raw.icon_calendar_tick, aa.a(ew.class), false, 4);
            j.a(jVar, R.raw.icon_favorites_collection, aa.a(ht.class), false, 4);
            j.a(jVar, R.raw.icon_flag, aa.a(hz.class), false, 4);
            j.a(jVar, R.raw.icon_gif, aa.a(ih.class), false, 4);
            j.a(jVar, R.raw.icon_book_star, aa.a(ej.class), false, 4);
            j.a(jVar, R.raw.icon_chevron_down, aa.a(ez.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_left_right_rectangle, aa.a(dh.class), false, 4);
            j.a(jVar, R.raw.icon_accessibility, aa.a(ch.class), false, 4);
            j.a(jVar, R.raw.icon_arrow_to_down, aa.a(dj.class), false, 4);
            jVar.a(R.raw.icon_chevron_right_ltr, aa.a(ff.class), true);
            jVar.a(R.raw.icon_speaker_x_mark_ltr, aa.a(nl.class), true);
            j.a(jVar, R.raw.icon_chevron_up, aa.a(fj.class), false, 4);
            j.a(jVar, R.raw.icon_backspace, aa.a(dy.class), false, 4);
            j.a(jVar, R.raw.icon_sms, aa.a(ng.class), false, 4);
            j.a(jVar, R.raw.icon_video_on_video, aa.a(po.class), false, 4);
            j.a(jVar, R.raw.icon_artist, aa.a(du.class), false, 4);
            j.a(jVar, R.raw.icon_pin, aa.a(me.class), false, 4);
            j.a(jVar, R.raw.icon_x_mark_on_doc, aa.a(py.class), false, 4);
            j.a(jVar, R.raw.icon_wallet_add_center, aa.a(pt.class), false, 4);
            j.a(jVar, R.raw.icon_x_mark_small, aa.a(pz.class), false, 4);
            j.a(jVar, R.raw.icon_filter, aa.a(hw.class), false, 4);
            j.a(jVar, R.raw.icon_post, aa.a(mn.class), false, 4);
            j.a(jVar, R.raw.icon_lock, aa.a(kv.class), false, 4);
            j.a(jVar, R.raw.icon_shopping_bag_plus, aa.a(nc.class), false, 4);
            j.a(jVar, R.raw.icon_control, aa.a(gs.class), false, 4);
            j.a(jVar, R.raw.icon_headset, aa.a(ip.class), false, 4);
            jVar.a(R.raw.icon_speaker_2_slash_ltr, aa.a(nj.class), true);
            j.a(jVar, R.raw.icon_fire, aa.a(hx.class), false, 4);
            j.a(jVar, R.raw.icon_bubble_right_tick, aa.a(et.class), false, 4);
            jVar.a(R.raw.icon_lines_horizontal_decrease_rectangle_ltr, aa.a(kp.class), true);
            jVar.a(R.raw.icon_speaker_2_fill_ltr, aa.a(nh.class), true);
            jVar.a(R.raw.icon_chevron_right_offset_small_ltr, aa.a(fi.class), true);
            j.a(jVar, R.raw.icon_create_group, aa.a(gw.class), false, 4);
            j.a(jVar, R.raw.icon_link, aa.a(kq.class), false, 4);
            j.a(jVar, R.raw.icon_pen, aa.a(lq.class), false, 4);
            j.a(jVar, R.raw.icon_briefcase_plus, aa.a(en.class), false, 4);
            j.a(jVar, R.raw.icon_low_battery, aa.a(ky.class), false, 4);
            j.a(jVar, R.raw.icon_tab_following, aa.a(oh.class), false, 4);
            j.a(jVar, R.raw.icon_tab_account, aa.a(ny.class), false, 4);
            j.a(jVar, R.raw.icon_tab_discover_hash, aa.a(oc.class), false, 4);
            j.a(jVar, R.raw.icon_tab_explore_fill, aa.a(of.class), false, 4);
            j.a(jVar, R.raw.icon_tab_inbox_fill, aa.a(oo.class), false, 4);
            j.a(jVar, R.raw.icon_tab_live_fill, aa.a(oq.class), false, 4);
            j.a(jVar, R.raw.icon_tab_home, aa.a(ol.class), false, 4);
            j.a(jVar, R.raw.icon_tab_heart, aa.a(oj.class), false, 4);
            j.a(jVar, R.raw.icon_tab_explore, aa.a(oe.class), false, 4);
            j.a(jVar, R.raw.icon_tab_arrow_counter_clockwise_fill, aa.a(ob.class), false, 4);
            j.a(jVar, R.raw.icon_tab_feed_fill, aa.a(og.class), false, 4);
            j.a(jVar, R.raw.icon_tab_discover_hash_fill, aa.a(od.class), false, 4);
            j.a(jVar, R.raw.icon_tab_account_fill, aa.a(nz.class), false, 4);
            j.a(jVar, R.raw.icon_tab_inbox, aa.a(on.class), false, 4);
            j.a(jVar, R.raw.icon_tab_heart_fill, aa.a(ok.class), false, 4);
            j.a(jVar, R.raw.icon_tab_following_fill, aa.a(oi.class), false, 4);
            j.a(jVar, R.raw.icon_tab_arrow_counter_clockwise, aa.a(oa.class), false, 4);
            j.a(jVar, R.raw.icon_tab_live, aa.a(op.class), false, 4);
            j.a(jVar, R.raw.icon_tab_home_fill, aa.a(om.class), false, 4);
            j.a(jVar, R.raw.icon_youtube, null, false, 6);
            j.a(jVar, R.raw.icon_arrow_top_fill, null, false, 6);
            j.a(jVar, R.raw.icon_chervon_down_double, null, false, 6);
            j.a(jVar, R.raw.icon_a_rectangle_on_rectangle, null, false, 6);
            j.a(jVar, R.raw.icon_arrow_clockwise, null, false, 6);
            j.a(jVar, R.raw.icon_clock_fill, null, false, 6);
            j.a(jVar, R.raw.icon_heart_grid, null, false, 6);
            j.a(jVar, R.raw.icon_compass, null, false, 6);
            j.a(jVar, R.raw.icon_document_umbrella, null, false, 6);
            j.a(jVar, R.raw.icon_flag_star, null, false, 6);
            j.a(jVar, R.raw.icon_globe_tick, null, false, 6);
            j.a(jVar, R.raw.icon_house_building, null, false, 6);
            j.a(jVar, R.raw.icon_house_play, null, false, 6);
            j.a(jVar, R.raw.icon_magnifying_glass_offset, null, false, 6);
            j.a(jVar, R.raw.icon_person_unlock, null, false, 6);
            j.a(jVar, R.raw.icon_person_x_mark, null, false, 6);
            j.a(jVar, R.raw.icon_plus_person, null, false, 6);
            j.a(jVar, R.raw.icon_raising_star_fill, null, false, 6);
            j.a(jVar, R.raw.icon_raising_star_slash, null, false, 6);
            j.a(jVar, R.raw.icon_raising_star, null, false, 6);
            j.a(jVar, R.raw.icon_repost_tick, null, false, 6);
            j.a(jVar, R.raw.icon_repost, null, false, 6);
            j.a(jVar, R.raw.icon_thumbs_down, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_trash_bin, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_stitch, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_playlist, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_playlist_fill, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_lock_keyhole, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_line_chart, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_flag, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_flag_star, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_broken_heart, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_bookmark, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_bookmark_fill, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_arrow_to_bottom, null, false, 6);
            j.a(jVar, R.raw.icon_3pt_arrow_stroke_to_top, null, false, 6);
            j.a(jVar, R.raw.icon_2pt_paperplane, null, false, 6);
            j.a(jVar, R.raw.icon_2pt_person_plus, null, false, 6);
            j.a(jVar, R.raw.icon_2pt_plus_person, null, false, 6);
            j.a(jVar, R.raw.icon_2pt_qa_ltr, null, true, 2);
            j.a(jVar, R.raw.icon_color_creator_next, null, false, 6);
            j.a(jVar, R.raw.icon_color_fire, null, false, 6);
            j.a(jVar, R.raw.icon_play_circle, null, false, 6);
            j.a(jVar, R.raw.icon_color_qa_fill_ltr, null, true, 2);
            j.a(jVar, R.raw.icon_large_bubble_bookmark, null, false, 6);
            j.a(jVar, R.raw.icon_large_contacts, null, false, 6);
            j.a(jVar, R.raw.icon_large_lightbulb, null, false, 6);
            j.a(jVar, R.raw.icon_large_map_pin, null, false, 6);
            j.a(jVar, R.raw.icon_color_contact, null, false, 6);
            j.a(jVar, R.raw.icon_video_star, null, false, 6);
            j.a(jVar, R.raw.icon_music_dsp1, null, false, 6);
            j.a(jVar, R.raw.icon_music_dsp2, null, false, 6);
            j.a(jVar, R.raw.icon_color_queue, null, false, 6);
            j.a(jVar, R.raw.icon_shuffle, null, false, 6);
        }
    }
}
