package com.a.b;

import android.util.SparseArray;
import com.bytedance.covode.number.Covode;
import com.bytedance.nita.api.a;
import com.bytedance.nita.api.e;
import com.bytedance.nita.api.f;
import com.bytedance.nita.api.g;
import com.zhiliaoapp.musically.R;
import java.util.HashMap;

public final class b {

    /* renamed from: a  reason: collision with root package name */
    private static final SparseArray<a> f4929a;

    /* renamed from: b  reason: collision with root package name */
    private static final HashMap<String, a> f4930b;

    static {
        Covode.recordClassIndex(2038);
        SparseArray<a> sparseArray = new SparseArray<>();
        f4929a = sparseArray;
        HashMap<String, a> hashMap = new HashMap<>();
        f4930b = hashMap;
        if (c.f4932b != null) {
            a aVar = new a("homepage_common_activity_main", new int[]{R.layout.a3e}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, R.style.o1, 1);
            sparseArray.put(R.layout.a3e, aVar);
            hashMap.put("homepage_common_activity_main", aVar);
            com.bytedance.nita.a.f41606c.a(aVar);
            a aVar2 = new a("legacy_fragment_page_container", new int[]{R.layout.ajc}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.ajc, aVar2);
            hashMap.put("legacy_fragment_page_container", aVar2);
            com.bytedance.nita.a.f41606c.a(aVar2);
            a aVar3 = new a("awemenotice_mus_new_popview_notification", new int[]{R.layout.le}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.le, aVar3);
            hashMap.put("awemenotice_mus_new_popview_notification", aVar3);
            com.bytedance.nita.a.f41606c.a(aVar3);
            a aVar4 = new a("homepage_common_fragment_main_page", new int[]{R.layout.a3n}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.a3n, aVar4);
            hashMap.put("homepage_common_fragment_main_page", aVar4);
            com.bytedance.nita.a.f41606c.a(aVar4);
            a aVar5 = new a("homepage_common_fragment_main_page_opt", new int[]{R.layout.a3o}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.a3o, aVar5);
            hashMap.put("homepage_common_fragment_main_page_opt", aVar5);
            com.bytedance.nita.a.f41606c.a(aVar5);
            a aVar6 = new a("homepage_common_black_mask_layer_tmp_wrapper", new int[]{R.layout.a3h}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.a3h, aVar6);
            hashMap.put("homepage_common_black_mask_layer_tmp_wrapper", aVar6);
            com.bytedance.nita.a.f41606c.a(aVar6);
            a aVar7 = new a("homepage_common_ad_half_web_page_container_tmp_wrapper", new int[]{R.layout.a3g}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.a3g, aVar7);
            hashMap.put("homepage_common_ad_half_web_page_container_tmp_wrapper", aVar7);
            com.bytedance.nita.a.f41606c.a(aVar7);
            a aVar8 = new a("homepage_common_fragment_main", new int[]{R.layout.a3l}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.a3l, aVar8);
            hashMap.put("homepage_common_fragment_main", aVar8);
            com.bytedance.nita.a.f41606c.a(aVar8);
            a aVar9 = new a("homepage_common_fragment_main_opt", new int[]{R.layout.a3m}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.a3m, aVar9);
            hashMap.put("homepage_common_fragment_main_opt", aVar9);
            com.bytedance.nita.a.f41606c.a(aVar9);
            a aVar10 = new a("homepage_common_view_main_tab_item_follow", new int[]{R.layout.a44}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.a44, aVar10);
            hashMap.put("homepage_common_view_main_tab_item_follow", aVar10);
            com.bytedance.nita.a.f41606c.a(aVar10);
            a aVar11 = new a("homepage_common_view_main_tab_item_follow_opt", new int[]{R.layout.a45}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.a45, aVar11);
            hashMap.put("homepage_common_view_main_tab_item_follow_opt", aVar11);
            com.bytedance.nita.a.f41606c.a(aVar11);
            a aVar12 = new a("common_feed_fragment_feed", new int[]{R.layout.s2}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.s2, aVar12);
            hashMap.put("common_feed_fragment_feed", aVar12);
            com.bytedance.nita.a.f41606c.a(aVar12);
            a aVar13 = new a("common_feed_fragment_feed_opt", new int[]{R.layout.s7}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.s7, aVar13);
            hashMap.put("common_feed_fragment_feed_opt", aVar13);
            com.bytedance.nita.a.f41606c.a(aVar13);
            a aVar14 = new a("common_feed_item_feed", new int[]{R.layout.sa}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.sa, aVar14);
            hashMap.put("common_feed_item_feed", aVar14);
            com.bytedance.nita.a.f41606c.a(aVar14);
            a aVar15 = new a("story_item_story_list", new int[]{R.layout.b2_}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.b2_, aVar15);
            hashMap.put("story_item_story_list", aVar15);
            com.bytedance.nita.a.f41606c.a(aVar15);
            a aVar16 = new a("common_feed_view_video_caution", new int[]{R.layout.to}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.to, aVar16);
            hashMap.put("common_feed_view_video_caution", aVar16);
            com.bytedance.nita.a.f41606c.a(aVar16);
            a aVar17 = new a("common_feed_anchor_multi_anchor", new int[]{R.layout.ru}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.ru, aVar17);
            hashMap.put("common_feed_anchor_multi_anchor", aVar17);
            com.bytedance.nita.a.f41606c.a(aVar17);
            a aVar18 = new a("common_feed_layout_video_desc", new int[]{R.layout.t1}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.t1, aVar18);
            hashMap.put("common_feed_layout_video_desc", aVar18);
            com.bytedance.nita.a.f41606c.a(aVar18);
            a aVar19 = new a("layout_video_multi_tag", new int[]{R.layout.aj5}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.aj5, aVar19);
            hashMap.put("layout_video_multi_tag", aVar19);
            com.bytedance.nita.a.f41606c.a(aVar19);
            a aVar20 = new a("common_feed_layout_video_digg", new int[]{R.layout.t2}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.t2, aVar20);
            hashMap.put("common_feed_layout_video_digg", aVar20);
            com.bytedance.nita.a.f41606c.a(aVar20);
            a aVar21 = new a("common_feed_view_video_progress_bar", new int[]{R.layout.tp}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.tp, aVar21);
            hashMap.put("common_feed_view_video_progress_bar", aVar21);
            com.bytedance.nita.a.f41606c.a(aVar21);
            a aVar22 = new a("common_feed_layout_video_comment_count", new int[]{R.layout.sz}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.sz, aVar22);
            hashMap.put("common_feed_layout_video_comment_count", aVar22);
            com.bytedance.nita.a.f41606c.a(aVar22);
            a aVar23 = new a("common_feed_layout_video_share", new int[]{R.layout.t6}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.t6, aVar23);
            hashMap.put("common_feed_layout_video_share", aVar23);
            com.bytedance.nita.a.f41606c.a(aVar23);
            a aVar24 = new a("common_feed_layout_video_more", new int[]{R.layout.t5}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.t5, aVar24);
            hashMap.put("common_feed_layout_video_more", aVar24);
            com.bytedance.nita.a.f41606c.a(aVar24);
            a aVar25 = new a("common_feed_addiction_hint", new int[]{R.layout.rs}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.rs, aVar25);
            hashMap.put("common_feed_addiction_hint", aVar25);
            com.bytedance.nita.a.f41606c.a(aVar25);
            a aVar26 = new a("common_feed_layout_feed_avatar", new int[]{R.layout.sl}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.sl, aVar26);
            hashMap.put("common_feed_layout_feed_avatar", aVar26);
            com.bytedance.nita.a.f41606c.a(aVar26);
            a aVar27 = new a("common_feed_layout_video_title_with_relation", new int[]{R.layout.t9}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.t9, aVar27);
            hashMap.put("common_feed_layout_video_title_with_relation", aVar27);
            com.bytedance.nita.a.f41606c.a(aVar27);
            a aVar28 = new a("common_feed_layout_video_title_music", new int[]{R.layout.t8}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.t8, aVar28);
            hashMap.put("common_feed_layout_video_title_music", aVar28);
            com.bytedance.nita.a.f41606c.a(aVar28);
            a aVar29 = new a("common_feed_layout_video_cover_music", new int[]{R.layout.t0}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.t0, aVar29);
            hashMap.put("common_feed_layout_video_cover_music", aVar29);
            com.bytedance.nita.a.f41606c.a(aVar29);
            a aVar30 = new a("aweme_comment_fragment_comment_list", new int[]{R.layout.i_}, e.AT_ONCE, g.INFINITE, f.SINGLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.i_, aVar30);
            hashMap.put("aweme_comment_fragment_comment_list", aVar30);
            com.bytedance.nita.a.f41606c.a(aVar30);
            a aVar31 = new a("detail_feed_activity_video_detail", new int[]{R.layout.wa}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.wa, aVar31);
            hashMap.put("detail_feed_activity_video_detail", aVar31);
            com.bytedance.nita.a.f41606c.a(aVar31);
            a aVar32 = new a("detail_feed_fragment_detail_page", new int[]{R.layout.wl}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.wl, aVar32);
            hashMap.put("detail_feed_fragment_detail_page", aVar32);
            com.bytedance.nita.a.f41606c.a(aVar32);
            a aVar33 = new a("aweme_comment_fragment_input_detail", new int[]{R.layout.f366if}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.f366if, aVar33);
            hashMap.put("aweme_comment_fragment_input_detail", aVar33);
            com.bytedance.nita.a.f41606c.a(aVar33);
            a aVar34 = new a("detail_feed_insights_bottom", new int[]{R.layout.wm}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.wm, aVar34);
            hashMap.put("detail_feed_insights_bottom", aVar34);
            com.bytedance.nita.a.f41606c.a(aVar34);
            a aVar35 = new a("profile_fragment_user_mt", new int[]{R.layout.aoe}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.aoe, aVar35);
            hashMap.put("profile_fragment_user_mt", aVar35);
            com.bytedance.nita.a.f41606c.a(aVar35);
            a aVar36 = new a("detail_feed_video_seek_bar", new int[]{R.layout.wz}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.wz, aVar36);
            hashMap.put("detail_feed_video_seek_bar", aVar36);
            com.bytedance.nita.a.f41606c.a(aVar36);
            a aVar37 = new a("profile_fragment_aweme_list_mus", new int[]{R.layout.anx}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 2);
            sparseArray.put(R.layout.anx, aVar37);
            hashMap.put("profile_fragment_aweme_list_mus", aVar37);
            com.bytedance.nita.a.f41606c.a(aVar37);
            a aVar38 = new a("discovery_search_fragment_reduce_overdraw", new int[]{R.layout.y0}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.y0, aVar38);
            hashMap.put("discovery_search_fragment_reduce_overdraw", aVar38);
            com.bytedance.nita.a.f41606c.a(aVar38);
            a aVar39 = new a("discovery_fragment_tab_reduce_overdraw", new int[]{R.layout.xp}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.xp, aVar39);
            hashMap.put("discovery_fragment_tab_reduce_overdraw", aVar39);
            com.bytedance.nita.a.f41606c.a(aVar39);
            a aVar40 = new a("aweme_comment_fragment_input_comment", new int[]{R.layout.id}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.id, aVar40);
            hashMap.put("aweme_comment_fragment_input_comment", aVar40);
            com.bytedance.nita.a.f41606c.a(aVar40);
            a aVar41 = new a("layout_video_expose_sharer", new int[]{R.layout.aj3}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.aj3, aVar41);
            hashMap.put("layout_video_expose_sharer", aVar41);
            com.bytedance.nita.a.f41606c.a(aVar41);
            a aVar42 = new a("mix_feed_mix_list_item", new int[]{R.layout.al0}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.al0, aVar42);
            hashMap.put("mix_feed_mix_list_item", aVar42);
            com.bytedance.nita.a.f41606c.a(aVar42);
            a aVar43 = new a("profile_item_aweme", new int[]{R.layout.aoi}, e.AT_ONCE, g.INFINITE, f.MUTIPLE, c.f4932b.a(), 1);
            sparseArray.put(R.layout.aoi, aVar43);
            hashMap.put("profile_item_aweme", aVar43);
            com.bytedance.nita.a.f41606c.a(aVar43);
        }
    }

    public static a a(int i2) {
        return f4929a.get(i2);
    }

    public static a a(String str) {
        return f4930b.get(str);
    }
}
