package com.a.b;

import android.content.Context;
import android.util.SparseArray;
import android.view.View;
import android.view.ViewGroup;
import com.a.a.a;
import com.a.a.aa;
import com.a.a.ab;
import com.a.a.ac;
import com.a.a.ad;
import com.a.a.ae;
import com.a.a.af;
import com.a.a.ag;
import com.a.a.ah;
import com.a.a.ai;
import com.a.a.aj;
import com.a.a.ak;
import com.a.a.al;
import com.a.a.am;
import com.a.a.an;
import com.a.a.ao;
import com.a.a.ap;
import com.a.a.aq;
import com.a.a.ar;
import com.a.a.as;
import com.a.a.at;
import com.a.a.au;
import com.a.a.av;
import com.a.a.aw;
import com.a.a.ax;
import com.a.a.ay;
import com.a.a.az;
import com.a.a.b;
import com.a.a.ba;
import com.a.a.bb;
import com.a.a.bc;
import com.a.a.bd;
import com.a.a.be;
import com.a.a.bf;
import com.a.a.bg;
import com.a.a.bh;
import com.a.a.bi;
import com.a.a.bj;
import com.a.a.bk;
import com.a.a.bl;
import com.a.a.bm;
import com.a.a.bn;
import com.a.a.bo;
import com.a.a.bp;
import com.a.a.bq;
import com.a.a.br;
import com.a.a.bs;
import com.a.a.bt;
import com.a.a.bu;
import com.a.a.bv;
import com.a.a.bw;
import com.a.a.bx;
import com.a.a.by;
import com.a.a.bz;
import com.a.a.c;
import com.a.a.ca;
import com.a.a.cb;
import com.a.a.cc;
import com.a.a.cd;
import com.a.a.ce;
import com.a.a.cf;
import com.a.a.cg;
import com.a.a.ch;
import com.a.a.ci;
import com.a.a.cj;
import com.a.a.ck;
import com.a.a.cl;
import com.a.a.cm;
import com.a.a.cn;
import com.a.a.co;
import com.a.a.cp;
import com.a.a.cq;
import com.a.a.cr;
import com.a.a.d;
import com.a.a.e;
import com.a.a.g;
import com.a.a.h;
import com.a.a.i;
import com.a.a.j;
import com.a.a.k;
import com.a.a.l;
import com.a.a.m;
import com.a.a.n;
import com.a.a.o;
import com.a.a.p;
import com.a.a.q;
import com.a.a.r;
import com.a.a.s;
import com.a.a.t;
import com.a.a.u;
import com.a.a.v;
import com.a.a.w;
import com.a.a.x;
import com.a.a.y;
import com.a.a.z;
import com.bytedance.covode.number.Covode;
import com.zhiliaoapp.musically.R;

public final class f {

    /* renamed from: a  reason: collision with root package name */
    static SparseArray<e> f4951a;

    static {
        Covode.recordClassIndex(2047);
        SparseArray<e> sparseArray = new SparseArray<>();
        f4951a = sparseArray;
        sparseArray.put(R.layout.qt, new ac());
        f4951a.put(R.layout.bf4, new cq());
        f4951a.put(R.layout.al0, new ci());
        f4951a.put(R.layout.b91, new cj());
        f4951a.put(R.layout.xp, new bq());
        f4951a.put(R.layout.qs, new ab());
        f4951a.put(R.layout.bib, new cr());
        f4951a.put(R.layout.b9o, new cn());
        f4951a.put(R.layout.b9k, new cm());
        f4951a.put(R.layout.b9j, new cl());
        f4951a.put(R.layout.b9f, new ck());
        f4951a.put(R.layout.y0, new br());
        f4951a.put(R.layout.rs, new af());
        f4951a.put(R.layout.rp, new ad());
        f4951a.put(R.layout.rq, new ae());
        f4951a.put(R.layout.o7, new g());
        f4951a.put(R.layout.b9s, new co());
        f4951a.put(R.layout.s9, new al());
        f4951a.put(R.layout.sa, new an());
        f4951a.put(R.layout.s_, new am());
        f4951a.put(R.layout.s5, new aj());
        f4951a.put(R.layout.s4, new ai());
        f4951a.put(R.layout.s7, new ak());
        f4951a.put(R.layout.s3, new ah());
        f4951a.put(R.layout.s2, new ag());
        f4951a.put(R.layout.ajc, new ch());
        f4951a.put(R.layout.sn, new as());
        f4951a.put(R.layout.i_, new b());
        f4951a.put(R.layout.sk, new ap());
        f4951a.put(R.layout.sm, new ar());
        f4951a.put(R.layout.sl, new aq());
        f4951a.put(R.layout.aj5, new cg());
        f4951a.put(R.layout.i5, new a());
        f4951a.put(R.layout.le, new e());
        f4951a.put(R.layout.sb, new ao());
        f4951a.put(R.layout.aj3, new cf());
        f4951a.put(R.layout.a3h, new bu());
        f4951a.put(R.layout.agb, new ce());
        f4951a.put(R.layout.a3g, new bt());
        f4951a.put(R.layout.wm, new bo());
        f4951a.put(R.layout.a70, new cd());
        f4951a.put(R.layout.pp, new j());
        f4951a.put(R.layout.t6, new ba());
        f4951a.put(R.layout.t5, new az());
        f4951a.put(R.layout.po, new i());
        f4951a.put(R.layout.t0, new aw());
        f4951a.put(R.layout.sz, new av());
        f4951a.put(R.layout.pl, new h());
        f4951a.put(R.layout.t2, new ay());
        f4951a.put(R.layout.t1, new ax());
        f4951a.put(R.layout.a3e, new bs());
        f4951a.put(R.layout.sw, new au());
        f4951a.put(R.layout.sv, new at());
        f4951a.put(R.layout.id, new c());
        f4951a.put(R.layout.wa, new bn());
        f4951a.put(R.layout.q3, new t());
        f4951a.put(R.layout.wz, new bp());
        f4951a.put(R.layout.q5, new v());
        f4951a.put(R.layout.tl, new bh());
        f4951a.put(R.layout.q4, new u());
        f4951a.put(R.layout.tf, new bf());
        f4951a.put(R.layout.te, new be());
        f4951a.put(R.layout.a3s, new bz());
        f4951a.put(R.layout.q1, new s());
        f4951a.put(R.layout.tg, new bg());
        f4951a.put(R.layout.pv, new p());
        f4951a.put(R.layout.pu, new o());
        f4951a.put(R.layout.a3o, new by());
        f4951a.put(R.layout.td, new bd());
        f4951a.put(R.layout.px, new r());
        f4951a.put(R.layout.pw, new q());
        f4951a.put(R.layout.pr, new l());
        f4951a.put(R.layout.t8, new bb());
        f4951a.put(R.layout.a3l, new bv());
        f4951a.put(R.layout.pq, new k());
        f4951a.put(R.layout.pt, new n());
        f4951a.put(R.layout.be1, new cp());
        f4951a.put(R.layout.a3n, new bx());
        f4951a.put(R.layout.ps, new m());
        f4951a.put(R.layout.t9, new bc());
        f4951a.put(R.layout.a3m, new bw());
        f4951a.put(R.layout.qe, new aa());
        f4951a.put(R.layout.jd, new d());
        f4951a.put(R.layout.tr, new bl());
        f4951a.put(R.layout.a45, new cb());
        f4951a.put(R.layout.tq, new bk());
        f4951a.put(R.layout.a44, new ca());
        f4951a.put(R.layout.qc, new z());
        f4951a.put(R.layout.qb, new y());
        f4951a.put(R.layout.ts, new bm());
        f4951a.put(R.layout.a46, new cc());
        f4951a.put(R.layout.mp, new com.a.a.f());
        f4951a.put(R.layout.q6, new w());
        f4951a.put(R.layout.tp, new bj());
        f4951a.put(R.layout.q8, new x());
        f4951a.put(R.layout.to, new bi());
    }

    public static View a(e eVar, Context context, ViewGroup viewGroup, boolean z) {
        return eVar.a(context, viewGroup, z);
    }
}
