package com.bytedance.android.live.service.initializer;

import com.bytedance.android.live.actionhandler.IActionHandlerService;
import com.bytedance.android.live.adminsetting.b;
import com.bytedance.android.live.b.g;
import com.bytedance.android.live.broadcast.api.IBroadcastService;
import com.bytedance.android.live.effect.api.IEffectService;
import com.bytedance.android.live.gift.IGiftService;
import com.bytedance.android.live.p.h;
import com.bytedance.android.live.s.e;
import com.bytedance.android.live.slot.ISlotService;
import com.bytedance.android.live.t.a;
import com.bytedance.android.live.wallet.IWalletService;
import com.bytedance.android.live.wallet.v;
import com.bytedance.android.livesdk.BarrageServiceImpl;
import com.bytedance.android.livesdk.ad.j;
import com.bytedance.android.livesdk.as;
import com.bytedance.android.livesdk.function.m;
import com.bytedance.android.livesdk.hashtag.d;
import com.bytedance.android.livesdk.k;
import com.bytedance.android.livesdk.p;
import com.bytedance.android.livesdk.qa.z;
import com.bytedance.android.livesdk.share.f;
import com.bytedance.android.livesdk.t.c;
import com.bytedance.android.livesdk.toolbar.l;
import com.bytedance.android.livesdk.usercard.al;
import com.bytedance.android.livesdk.userinfowidget.aa;
import com.bytedance.android.livesdk.usermanage.i;
import com.bytedance.android.message.IMessageService;
import com.bytedance.covode.number.Covode;

public final class ServiceInitializer {
    static {
        Covode.recordClassIndex(6948);
    }

    public static void init() {
        k kVar = new k();
        kVar.onInit();
        a.a(IGiftService.class, kVar);
        com.bytedance.android.livesdk.actionhandler.a aVar = new com.bytedance.android.livesdk.actionhandler.a();
        aVar.onInit();
        a.a(IActionHandlerService.class, aVar);
        com.bytedance.android.livesdk.a.a aVar2 = new com.bytedance.android.livesdk.a.a();
        aVar2.onInit();
        a.a(b.class, aVar2);
        com.bytedance.android.livesdk.definition.b bVar = new com.bytedance.android.livesdk.definition.b();
        bVar.onInit();
        a.a(com.bytedance.android.live.d.b.class, bVar);
        c cVar = new c();
        cVar.onInit();
        a.a(com.bytedance.android.live.g.a.class, cVar);
        d dVar = new d();
        dVar.onInit();
        a.a(com.bytedance.android.live.h.b.class, dVar);
        com.bytedance.android.livesdk.microom.a aVar3 = new com.bytedance.android.livesdk.microom.a();
        aVar3.onInit();
        a.a(com.bytedance.android.live.j.a.class, aVar3);
        j jVar = new j();
        jVar.onInit();
        a.a(com.bytedance.android.live.k.a.class, jVar);
        com.bytedance.android.livesdk.af.b bVar2 = new com.bytedance.android.livesdk.af.b();
        bVar2.onInit();
        a.a(com.bytedance.android.live.l.b.class, bVar2);
        m mVar = new m();
        mVar.onInit();
        a.a(com.bytedance.android.live.f.a.class, mVar);
        f fVar = new f();
        fVar.onInit();
        a.a(com.bytedance.android.live.share.c.class, fVar);
        com.bytedance.android.livesdk.subscribe.b bVar3 = new com.bytedance.android.livesdk.subscribe.b();
        bVar3.onInit();
        a.a(com.bytedance.android.live.o.a.class, bVar3);
        l lVar = new l();
        lVar.onInit();
        a.a(h.class, lVar);
        al alVar = new al();
        alVar.onInit();
        a.a(com.bytedance.android.live.q.a.class, alVar);
        aa aaVar = new aa();
        aaVar.onInit();
        a.a(com.bytedance.android.live.r.a.class, aaVar);
        i iVar = new i();
        iVar.onInit();
        a.a(e.class, iVar);
        v vVar = new v();
        vVar.onInit();
        a.a(IWalletService.class, vVar);
        com.bytedance.android.live.broadcast.b bVar4 = new com.bytedance.android.live.broadcast.b();
        bVar4.onInit();
        a.a(IBroadcastService.class, bVar4);
        com.bytedance.android.livesdk.survey.f fVar2 = new com.bytedance.android.livesdk.survey.f();
        fVar2.onInit();
        a.a(com.bytedance.android.livesdk.survey.a.class, fVar2);
        com.bytedance.android.livesdk.watch.f fVar3 = new com.bytedance.android.livesdk.watch.f();
        fVar3.onInit();
        a.a(com.bytedance.android.livesdk.watch.d.class, fVar3);
        com.bytedance.android.live.i.a aVar4 = new com.bytedance.android.live.i.a();
        aVar4.onInit();
        a.a(com.bytedance.android.live.i.a.d.class, aVar4);
        as asVar = new as();
        asVar.onInit();
        a.a(IMessageService.class, asVar);
        com.bytedance.android.livesdk.ae.a aVar5 = new com.bytedance.android.livesdk.ae.a();
        aVar5.onInit();
        a.a(com.bytedance.android.live.b.f.class, aVar5);
        com.bytedance.android.livesdk.ae.b bVar5 = new com.bytedance.android.livesdk.ae.b();
        bVar5.onInit();
        a.a(g.class, bVar5);
        com.bytedance.android.livesdk.lynx.e eVar = new com.bytedance.android.livesdk.lynx.e();
        eVar.onInit();
        a.a(com.bytedance.android.livesdk.lynx.c.class, eVar);
        com.bytedance.android.livesdk.lynx.lynxcard.f fVar4 = new com.bytedance.android.livesdk.lynx.lynxcard.f();
        fVar4.onInit();
        a.a(com.bytedance.android.livesdk.lynx.lynxcard.b.class, fVar4);
        BarrageServiceImpl barrageServiceImpl = new BarrageServiceImpl();
        barrageServiceImpl.onInit();
        a.a(p.class, barrageServiceImpl);
        com.bytedance.android.livesdk.rank.impl.d dVar2 = new com.bytedance.android.livesdk.rank.impl.d();
        dVar2.onInit();
        a.a(com.bytedance.android.livesdk.rank.api.d.class, dVar2);
        com.bytedance.android.livesdk.v.a aVar6 = new com.bytedance.android.livesdk.v.a();
        aVar6.onInit();
        a.a(com.bytedance.android.live.c.b.class, aVar6);
        com.bytedance.android.live.b bVar6 = new com.bytedance.android.live.b();
        bVar6.onInit();
        a.a(com.bytedance.android.live.f.class, bVar6);
        com.bytedance.android.live.banner.a aVar7 = new com.bytedance.android.live.banner.a();
        aVar7.onInit();
        a.a(com.bytedance.android.live.banner.c.class, aVar7);
        com.bytedance.android.live.i iVar2 = new com.bytedance.android.live.i();
        iVar2.onInit();
        a.a(ISlotService.class, iVar2);
        com.bytedance.android.live.publicscreen.impl.a aVar8 = new com.bytedance.android.live.publicscreen.impl.a();
        aVar8.onInit();
        a.a(com.bytedance.android.live.publicscreen.a.e.class, aVar8);
        com.bytedance.android.livesdk.feed.tab.a aVar9 = new com.bytedance.android.livesdk.feed.tab.a();
        aVar9.onInit();
        a.a(com.bytedance.android.b.a.b.class, aVar9);
        com.bytedance.android.live.effect.c cVar2 = new com.bytedance.android.live.effect.c();
        cVar2.onInit();
        a.a(IEffectService.class, cVar2);
        z zVar = new z();
        zVar.onInit();
        a.a(com.bytedance.android.live.m.a.class, zVar);
        com.bytedance.android.live.liveinteract.linkroom.a aVar10 = new com.bytedance.android.live.liveinteract.linkroom.a();
        aVar10.onInit();
        a.a(com.bytedance.android.live.liveinteract.api.b.class, aVar10);
    }
}
