package com.bytedance.android.live.base.model.proto;

import com.bytedance.android.live.base.model.HashtagResponse;
import com.bytedance.android.live.base.model.ImageModel;
import com.bytedance.android.live.base.model.c.a;
import com.bytedance.android.live.base.model.d;
import com.bytedance.android.live.base.model.emoji.EmoteModel;
import com.bytedance.android.live.base.model.user.FollowInfo;
import com.bytedance.android.live.base.model.user.SubscribeBadge;
import com.bytedance.android.live.base.model.user.SubscribeInfo;
import com.bytedance.android.live.base.model.user.User;
import com.bytedance.android.live.liveinteract.multilive.c.s;
import com.bytedance.android.livesdk.boostcard.f;
import com.bytedance.android.livesdk.chatroom.interact.model.RivalsListExtra;
import com.bytedance.android.livesdk.chatroom.interact.model.i;
import com.bytedance.android.livesdk.chatroom.interact.model.k;
import com.bytedance.android.livesdk.chatroom.interact.model.o;
import com.bytedance.android.livesdk.chatroom.interact.model.t;
import com.bytedance.android.livesdk.chatroom.model.EnterRoomExtra;
import com.bytedance.android.livesdk.chatroom.model.m;
import com.bytedance.android.livesdk.chatroom.model.r;
import com.bytedance.android.livesdk.envelope.a.a;
import com.bytedance.android.livesdk.envelope.a.g;
import com.bytedance.android.livesdk.envelope.a.h;
import com.bytedance.android.livesdk.firstrecharge.b;
import com.bytedance.android.livesdk.firstrecharge.i;
import com.bytedance.android.livesdk.firstrecharge.j;
import com.bytedance.android.livesdk.gift.model.DoodleTemplate;
import com.bytedance.android.livesdk.gift.model.GiftPage;
import com.bytedance.android.livesdk.gift.model.Prop;
import com.bytedance.android.livesdk.gift.model.aa;
import com.bytedance.android.livesdk.gift.model.ab;
import com.bytedance.android.livesdk.gift.model.ac;
import com.bytedance.android.livesdk.gift.model.ad;
import com.bytedance.android.livesdk.gift.model.ae;
import com.bytedance.android.livesdk.gift.model.af;
import com.bytedance.android.livesdk.gift.model.ag;
import com.bytedance.android.livesdk.gift.model.ah;
import com.bytedance.android.livesdk.gift.model.ai;
import com.bytedance.android.livesdk.gift.model.aj;
import com.bytedance.android.livesdk.gift.model.ak;
import com.bytedance.android.livesdk.gift.model.al;
import com.bytedance.android.livesdk.gift.model.am;
import com.bytedance.android.livesdk.gift.model.an;
import com.bytedance.android.livesdk.gift.model.ao;
import com.bytedance.android.livesdk.gift.model.ap;
import com.bytedance.android.livesdk.gift.model.aq;
import com.bytedance.android.livesdk.gift.model.ar;
import com.bytedance.android.livesdk.gift.model.as;
import com.bytedance.android.livesdk.gift.model.at;
import com.bytedance.android.livesdk.gift.model.au;
import com.bytedance.android.livesdk.gift.model.av;
import com.bytedance.android.livesdk.gift.model.aw;
import com.bytedance.android.livesdk.gift.model.ax;
import com.bytedance.android.livesdk.gift.model.i;
import com.bytedance.android.livesdk.gift.model.l;
import com.bytedance.android.livesdk.gift.model.p;
import com.bytedance.android.livesdk.gift.model.u;
import com.bytedance.android.livesdk.gift.model.w;
import com.bytedance.android.livesdk.gift.model.x;
import com.bytedance.android.livesdk.gift.model.y;
import com.bytedance.android.livesdk.gift.model.z;
import com.bytedance.android.livesdk.model.FansClubData;
import com.bytedance.android.livesdk.model.FansClubMember;
import com.bytedance.android.livesdk.model.FeedItem;
import com.bytedance.android.livesdk.model.GameTag;
import com.bytedance.android.livesdk.model.GiftOperation;
import com.bytedance.android.livesdk.model.GiftTrayInfo;
import com.bytedance.android.livesdk.model.Hashtag;
import com.bytedance.android.livesdk.model.MaskLayer;
import com.bytedance.android.livesdk.model.RoomAuthOffReasons;
import com.bytedance.android.livesdk.model.RoomAuthStatus;
import com.bytedance.android.livesdk.model.RoomStats;
import com.bytedance.android.livesdk.model.ShortTouchItem;
import com.bytedance.android.livesdk.model.WarningTag;
import com.bytedance.android.livesdk.model.ba;
import com.bytedance.android.livesdk.model.bf;
import com.bytedance.android.livesdk.model.bq;
import com.bytedance.android.livesdk.model.cg;
import com.bytedance.android.livesdk.model.i;
import com.bytedance.android.livesdk.model.message.Cdo;
import com.bytedance.android.livesdk.model.message.FlexImageModel;
import com.bytedance.android.livesdk.model.message.RoomNotifyMessageExtra;
import com.bytedance.android.livesdk.model.message.al;
import com.bytedance.android.livesdk.model.message.ay;
import com.bytedance.android.livesdk.model.message.az;
import com.bytedance.android.livesdk.model.message.bb;
import com.bytedance.android.livesdk.model.message.bc;
import com.bytedance.android.livesdk.model.message.bd;
import com.bytedance.android.livesdk.model.message.be;
import com.bytedance.android.livesdk.model.message.bg;
import com.bytedance.android.livesdk.model.message.bh;
import com.bytedance.android.livesdk.model.message.bi;
import com.bytedance.android.livesdk.model.message.bj;
import com.bytedance.android.livesdk.model.message.bk;
import com.bytedance.android.livesdk.model.message.bl;
import com.bytedance.android.livesdk.model.message.bm;
import com.bytedance.android.livesdk.model.message.bn;
import com.bytedance.android.livesdk.model.message.bo;
import com.bytedance.android.livesdk.model.message.bp;
import com.bytedance.android.livesdk.model.message.br;
import com.bytedance.android.livesdk.model.message.bs;
import com.bytedance.android.livesdk.model.message.bt;
import com.bytedance.android.livesdk.model.message.bu;
import com.bytedance.android.livesdk.model.message.bv;
import com.bytedance.android.livesdk.model.message.bw;
import com.bytedance.android.livesdk.model.message.bx;
import com.bytedance.android.livesdk.model.message.by;
import com.bytedance.android.livesdk.model.message.bz;
import com.bytedance.android.livesdk.model.message.c;
import com.bytedance.android.livesdk.model.message.ca;
import com.bytedance.android.livesdk.model.message.cb;
import com.bytedance.android.livesdk.model.message.cc;
import com.bytedance.android.livesdk.model.message.cd;
import com.bytedance.android.livesdk.model.message.ce;
import com.bytedance.android.livesdk.model.message.cf;
import com.bytedance.android.livesdk.model.message.ch;
import com.bytedance.android.livesdk.model.message.ci;
import com.bytedance.android.livesdk.model.message.cj;
import com.bytedance.android.livesdk.model.message.ck;
import com.bytedance.android.livesdk.model.message.cl;
import com.bytedance.android.livesdk.model.message.cm;
import com.bytedance.android.livesdk.model.message.cn;
import com.bytedance.android.livesdk.model.message.co;
import com.bytedance.android.livesdk.model.message.cp;
import com.bytedance.android.livesdk.model.message.cq;
import com.bytedance.android.livesdk.model.message.cr;
import com.bytedance.android.livesdk.model.message.cs;
import com.bytedance.android.livesdk.model.message.ct;
import com.bytedance.android.livesdk.model.message.cu;
import com.bytedance.android.livesdk.model.message.cv;
import com.bytedance.android.livesdk.model.message.cw;
import com.bytedance.android.livesdk.model.message.cx;
import com.bytedance.android.livesdk.model.message.cy;
import com.bytedance.android.livesdk.model.message.cz;
import com.bytedance.android.livesdk.model.message.da;
import com.bytedance.android.livesdk.model.message.db;
import com.bytedance.android.livesdk.model.message.dc;
import com.bytedance.android.livesdk.model.message.dd;
import com.bytedance.android.livesdk.model.message.de;
import com.bytedance.android.livesdk.model.message.df;
import com.bytedance.android.livesdk.model.message.dg;
import com.bytedance.android.livesdk.model.message.dh;
import com.bytedance.android.livesdk.model.message.di;
import com.bytedance.android.livesdk.model.message.dj;
import com.bytedance.android.livesdk.model.message.dk;
import com.bytedance.android.livesdk.model.message.dl;
import com.bytedance.android.livesdk.model.message.dm;
import com.bytedance.android.livesdk.model.message.dn;
import com.bytedance.android.livesdk.model.message.dp;
import com.bytedance.android.livesdk.model.message.dq;
import com.bytedance.android.livesdk.model.message.dr;
import com.bytedance.android.livesdk.model.message.ds;
import com.bytedance.android.livesdk.model.message.dt;
import com.bytedance.android.livesdk.model.message.du;
import com.bytedance.android.livesdk.model.message.dv;
import com.bytedance.android.livesdk.model.message.dw;
import com.bytedance.android.livesdk.model.message.dx;
import com.bytedance.android.livesdk.model.message.dy;
import com.bytedance.android.livesdk.model.message.dz;
import com.bytedance.android.livesdk.model.message.e;
import com.bytedance.android.livesdk.model.message.ea;
import com.bytedance.android.livesdk.model.message.eb;
import com.bytedance.android.livesdk.model.message.ec;
import com.bytedance.android.livesdk.model.message.ed;
import com.bytedance.android.livesdk.model.message.ee;
import com.bytedance.android.livesdk.model.message.ef;
import com.bytedance.android.livesdk.model.message.eg;
import com.bytedance.android.livesdk.model.message.eh;
import com.bytedance.android.livesdk.model.message.ei;
import com.bytedance.android.livesdk.model.message.ej;
import com.bytedance.android.livesdk.model.message.ek;
import com.bytedance.android.livesdk.model.message.el;
import com.bytedance.android.livesdk.model.message.em;
import com.bytedance.android.livesdk.model.message.en;
import com.bytedance.android.livesdk.model.message.eo;
import com.bytedance.android.livesdk.model.message.ep;
import com.bytedance.android.livesdk.model.message.eq;
import com.bytedance.android.livesdk.model.message.er;
import com.bytedance.android.livesdk.model.message.es;
import com.bytedance.android.livesdk.model.message.et;
import com.bytedance.android.livesdk.model.message.eu;
import com.bytedance.android.livesdk.model.message.ev;
import com.bytedance.android.livesdk.model.message.ew;
import com.bytedance.android.livesdk.model.message.ex;
import com.bytedance.android.livesdk.model.message.ey;
import com.bytedance.android.livesdk.model.message.ez;
import com.bytedance.android.livesdk.model.message.fa;
import com.bytedance.android.livesdk.model.message.fb;
import com.bytedance.android.livesdk.model.message.fc;
import com.bytedance.android.livesdk.model.message.fd;
import com.bytedance.android.livesdk.model.message.fe;
import com.bytedance.android.livesdk.model.message.ff;
import com.bytedance.android.livesdk.model.message.fg;
import com.bytedance.android.livesdk.model.message.fh;
import com.bytedance.android.livesdk.model.message.fi;
import com.bytedance.android.livesdk.model.message.fj;
import com.bytedance.android.livesdk.model.message.fk;
import com.bytedance.android.livesdk.model.message.fl;
import com.bytedance.android.livesdk.model.message.fm;
import com.bytedance.android.livesdk.model.message.fn;
import com.bytedance.android.livesdk.model.message.fo;
import com.bytedance.android.livesdk.model.message.fp;
import com.bytedance.android.livesdk.model.message.fq;
import com.bytedance.android.livesdk.model.message.fr;
import com.bytedance.android.livesdk.model.message.fs;
import com.bytedance.android.livesdk.model.message.ft;
import com.bytedance.android.livesdk.model.message.fu;
import com.bytedance.android.livesdk.model.message.fv;
import com.bytedance.android.livesdk.model.message.fw;
import com.bytedance.android.livesdk.model.message.fx;
import com.bytedance.android.livesdk.model.message.fy;
import com.bytedance.android.livesdk.model.message.fz;
import com.bytedance.android.livesdk.model.message.ga;
import com.bytedance.android.livesdk.model.message.gb;
import com.bytedance.android.livesdk.model.message.gc;
import com.bytedance.android.livesdk.model.message.gd;
import com.bytedance.android.livesdk.model.message.ge;
import com.bytedance.android.livesdk.model.message.gf;
import com.bytedance.android.livesdk.model.message.gg;
import com.bytedance.android.livesdk.model.message.gh;
import com.bytedance.android.livesdk.model.message.gi;
import com.bytedance.android.livesdk.model.message.n;
import com.bytedance.android.livesdk.rank.api.model.CurrentRankListResponse;
import com.bytedance.android.livesdk.service.b.c;
import com.bytedance.android.livesdk.service.b.e;
import com.bytedance.android.livesdkapi.depend.model.live.BALinkStruct;
import com.bytedance.android.livesdkapi.depend.model.live.CommerceStruct;
import com.bytedance.android.livesdkapi.depend.model.live.ContinueRoomResponse;
import com.bytedance.android.livesdkapi.depend.model.live.FeedRoomLabel;
import com.bytedance.android.livesdkapi.depend.model.live.LiveCoreSDKData;
import com.bytedance.android.livesdkapi.depend.model.live.Room;
import com.bytedance.android.livesdkapi.depend.model.live.StreamUrl;
import com.bytedance.android.livesdkapi.depend.model.live.n;
import com.bytedance.android.livesdkapi.depend.model.live.q;
import com.bytedance.android.livesdkapi.depend.model.live.s;
import com.bytedance.android.livesdkapi.depend.model.live.v;
import com.bytedance.android.livesdkapi.depend.model.report.ReportCommitData;
import com.bytedance.android.livesdkapi.h.e;
import com.bytedance.covode.number.Covode;
import emotes.model.EmoteListResult;
import emotes.model.SubEmoteDetailResult;
import java.util.HashMap;

public final class ProtocolBuffersCollector {
    static {
        Covode.recordClassIndex(3622);
    }

    public static void init() {
        HashMap hashMap = new HashMap();
        HashMap hashMap2 = new HashMap();
        hashMap.put(c.class, new e());
        hashMap.put(com.bytedance.android.livesdk.envelope.a.e.class, new h());
        hashMap.put(a.class, new g());
        hashMap.put(com.bytedance.android.livesdk.boostcard.c.class, new com.bytedance.android.livesdk.boostcard.g());
        hashMap.put(com.bytedance.android.livesdk.boostcard.e.class, new com.bytedance.android.livesdk.boostcard.h());
        hashMap.put(com.bytedance.android.livesdk.boostcard.a.class, new f());
        hashMap.put(com.bytedance.android.livesdk.firstrecharge.a.class, new com.bytedance.android.livesdk.firstrecharge.h());
        hashMap.put(b.class, new i());
        hashMap.put(com.bytedance.android.livesdk.firstrecharge.c.class, new j());
        hashMap.put(com.bytedance.android.live.liveinteract.multilive.c.g.class, new s());
        hashMap.put(EmoteListResult.class, new emotes.model.a());
        hashMap.put(SubEmoteDetailResult.class, new emotes.model.b());
        hashMap.put(CurrentRankListResponse.class, new com.bytedance.android.livesdk.rank.api.model.i());
        hashMap.put(com.bytedance.android.livesdk.rank.api.model.h.class, new com.bytedance.android.livesdk.rank.api.model.j());
        hashMap.put(com.bytedance.android.live.base.model.live.b.class, new com.bytedance.android.live.base.model.live.e());
        hashMap.put(com.bytedance.android.live.base.model.live.c.class, new com.bytedance.android.live.base.model.live.f());
        hashMap.put(com.bytedance.android.live.base.model.a.a.class, new com.bytedance.android.live.base.model.a.b());
        hashMap.put(com.bytedance.android.live.base.model.c.a.class, new com.bytedance.android.live.base.model.c.c());
        hashMap.put(m.class, new r());
        hashMap.put(a.C0099a.class, new com.bytedance.android.live.base.model.c.b());
        hashMap.put(com.bytedance.android.livesdk.gift.model.a.class, new z());
        hashMap.put(com.bytedance.android.livesdk.gift.model.e.class, new ad());
        hashMap.put(com.bytedance.android.livesdk.gift.model.f.class, new ae());
        hashMap.put(com.bytedance.android.livesdk.gift.model.g.class, new af());
        hashMap.put(com.bytedance.android.livesdk.gift.model.h.class, new ag());
        hashMap.put(com.bytedance.android.livesdk.gift.model.i.class, new ai());
        hashMap.put(i.a.class, new ah());
        hashMap.put(com.bytedance.android.livesdk.gift.model.j.class, new aj());
        hashMap.put(GiftPage.class, new ak());
        hashMap.put(l.class, new al());
        hashMap.put(com.bytedance.android.livesdk.gift.model.m.class, new am());
        hashMap.put(p.class, new an());
        hashMap.put(u.class, new ap());
        hashMap.put(w.class, new ar());
        hashMap.put(com.bytedance.android.livesdk.wallet.c.class, new com.bytedance.android.livesdk.wallet.h());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.class, new com.bytedance.android.livesdkapi.depend.model.live.u());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.b.class, new v());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.l.class, new com.bytedance.android.livesdkapi.depend.model.live.ag());
        hashMap.put(n.class, new com.bytedance.android.livesdkapi.depend.model.live.ah());
        hashMap.put(q.class, new com.bytedance.android.livesdkapi.depend.model.live.aj());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.r.class, new com.bytedance.android.livesdkapi.depend.model.live.ak());
        hashMap.put(ReportCommitData.class, new com.bytedance.android.livesdkapi.depend.model.report.a());
        hashMap.put(com.bytedance.android.livesdkapi.h.e.class, new com.bytedance.android.livesdkapi.h.h());
        hashMap.put(e.a.class, new com.bytedance.android.livesdkapi.h.g());
        hashMap.put(HashtagResponse.class, new d());
        hashMap.put(FollowInfo.class, new com.bytedance.android.live.base.model.user.e());
        hashMap.put(User.class, new com.bytedance.android.live.base.model.user.j());
        hashMap.put(SubscribeInfo.class, new com.bytedance.android.live.base.model.user.g());
        hashMap.put(User.b.class, new com.bytedance.android.live.base.model.user.i());
        hashMap.put(SubscribeBadge.class, new com.bytedance.android.live.base.model.user.f());
        hashMap.put(User.a.class, new com.bytedance.android.live.base.model.user.h());
        hashMap.put(ImageModel.class, new com.bytedance.android.live.base.model.f());
        hashMap.put(ImageModel.Content.class, new com.bytedance.android.live.base.model.e());
        hashMap.put(com.bytedance.android.live.base.model.emoji.c.class, new com.bytedance.android.live.base.model.emoji.d());
        hashMap.put(EmoteModel.class, new com.bytedance.android.live.base.model.emoji.e());
        hashMap.put(com.bytedance.android.livesdk.chatroom.interact.model.a.class, new com.bytedance.android.livesdk.chatroom.interact.model.j());
        hashMap.put(com.bytedance.android.livesdk.chatroom.interact.model.b.class, new k());
        hashMap.put(com.bytedance.android.livesdk.chatroom.interact.model.c.class, new com.bytedance.android.livesdk.chatroom.interact.model.l());
        hashMap.put(com.bytedance.android.livesdk.chatroom.interact.model.f.class, new o());
        hashMap.put(com.bytedance.android.livesdk.chatroom.interact.model.h.class, new com.bytedance.android.livesdk.chatroom.interact.model.p());
        hashMap.put(RivalsListExtra.class, new com.bytedance.android.livesdk.chatroom.interact.model.r());
        hashMap.put(RivalsListExtra.LogPbBean.class, new com.bytedance.android.livesdk.chatroom.interact.model.q());
        hashMap.put(com.bytedance.android.livesdk.chatroom.interact.model.i.class, new t());
        hashMap.put(i.a.class, new com.bytedance.android.livesdk.chatroom.interact.model.s());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.b.b.class, new com.bytedance.android.livesdk.chatroom.model.b.h());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.b.c.class, new com.bytedance.android.livesdk.chatroom.model.b.i());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.b.e.class, new com.bytedance.android.livesdk.chatroom.model.b.j());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.b.f.class, new com.bytedance.android.livesdk.chatroom.model.b.k());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.b.g.class, new com.bytedance.android.livesdk.chatroom.model.b.l());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.b.a.a.class, new com.bytedance.android.livesdk.chatroom.model.b.a.d());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.b.a.b.class, new com.bytedance.android.livesdk.chatroom.model.b.a.e());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.b.a.c.class, new com.bytedance.android.livesdk.chatroom.model.b.a.f());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.a.class, new com.bytedance.android.livesdk.chatroom.model.p());
        hashMap.put(EnterRoomExtra.class, new com.bytedance.android.livesdk.chatroom.model.q());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.d.a.class, new com.bytedance.android.livesdk.chatroom.model.d.b());
        hashMap.put(com.bytedance.android.livesdk.feed.feed.f.class, new com.bytedance.android.livesdk.feed.feed.h());
        hashMap.put(DoodleTemplate.class, new aa());
        hashMap.put(com.bytedance.android.livesdk.gift.model.c.class, new ab());
        hashMap.put(com.bytedance.android.livesdk.gift.model.d.class, new ac());
        hashMap.put(com.bytedance.android.livesdk.gift.model.q.class, new ao());
        hashMap.put(Prop.class, new aq());
        hashMap.put(x.class, new as());
        hashMap.put(x.c.class, new au());
        hashMap.put(x.a.class, new aw());
        hashMap.put(x.a.C0373a.class, new av());
        hashMap.put(x.b.class, new at());
        hashMap.put(y.class, new ax());
        hashMap.put(com.bytedance.android.livesdk.model.message.a.class, new cl());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.class, new cm());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.class, new co());
        hashMap.put(c.a.class, new cn());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.class, new cp());
        hashMap.put(com.bytedance.android.livesdk.model.message.e.class, new cr());
        hashMap.put(e.a.class, new cq());
        hashMap.put(com.bytedance.android.livesdk.model.message.g.class, new ct());
        hashMap.put(com.bytedance.android.livesdk.model.message.h.class, new cu());
        hashMap.put(com.bytedance.android.livesdk.model.message.i.class, new cv());
        hashMap.put(com.bytedance.android.livesdk.model.message.j.class, new cw());
        hashMap.put(com.bytedance.android.livesdk.model.message.k.class, new cx());
        hashMap.put(com.bytedance.android.livesdk.model.message.l.class, new cy());
        hashMap.put(com.bytedance.android.livesdk.model.message.m.class, new cz());
        hashMap.put(com.bytedance.android.livesdk.model.message.n.class, new db());
        hashMap.put(n.a.class, new da());
        hashMap.put(com.bytedance.android.livesdk.model.message.o.class, new dc());
        hashMap.put(com.bytedance.android.livesdk.model.message.p.class, new dd());
        hashMap.put(com.bytedance.android.livesdk.model.message.q.class, new de());
        hashMap.put(com.bytedance.android.livesdk.model.message.s.class, new df());
        hashMap.put(FlexImageModel.class, new dg());
        hashMap.put(com.bytedance.android.livesdk.model.message.t.class, new dh());
        hashMap.put(com.bytedance.android.livesdk.model.message.x.class, new dl());
        hashMap.put(com.bytedance.android.livesdk.model.message.y.class, new dm());
        hashMap.put(com.bytedance.android.livesdk.model.message.z.class, new dn());
        hashMap.put(com.bytedance.android.livesdk.model.message.aa.class, new Cdo());
        hashMap.put(com.bytedance.android.livesdk.model.message.ab.class, new dp());
        hashMap.put(com.bytedance.android.livesdk.model.message.ac.class, new dq());
        hashMap.put(com.bytedance.android.livesdk.model.message.ad.class, new dr());
        hashMap.put(com.bytedance.android.livesdk.model.message.ae.class, new ds());
        hashMap.put(com.bytedance.android.livesdk.model.message.ag.class, new du());
        hashMap.put(com.bytedance.android.livesdk.model.message.ah.class, new dv());
        hashMap.put(com.bytedance.android.livesdk.model.message.ai.class, new dw());
        hashMap.put(com.bytedance.android.livesdk.model.message.aj.class, new dx());
        hashMap.put(com.bytedance.android.livesdk.model.message.ak.class, new dy());
        hashMap.put(com.bytedance.android.livesdk.model.message.al.class, new ec());
        hashMap.put(al.b.class, new ea());
        hashMap.put(al.c.class, new eb());
        hashMap.put(al.a.class, new dz());
        hashMap.put(com.bytedance.android.livesdk.model.message.am.class, new ed());
        hashMap.put(com.bytedance.android.livesdk.model.message.an.class, new ee());
        hashMap.put(com.bytedance.android.livesdk.model.message.ao.class, new ef());
        hashMap.put(com.bytedance.android.livesdk.model.message.ap.class, new eg());
        hashMap.put(com.bytedance.android.livesdk.model.message.aq.class, new eh());
        hashMap.put(com.bytedance.android.livesdk.model.message.ar.class, new ei());
        hashMap.put(com.bytedance.android.livesdk.model.message.at.class, new ej());
        hashMap.put(com.bytedance.android.livesdk.model.message.aw.class, new el());
        hashMap.put(ay.class, new en());
        hashMap.put(ay.a.class, new em());
        hashMap.put(az.class, new ep());
        hashMap.put(az.a.class, new eo());
        hashMap.put(bb.class, new er());
        hashMap.put(bc.class, new es());
        hashMap.put(bd.class, new et());
        hashMap.put(be.class, new eu());
        hashMap.put(bg.class, new ex());
        hashMap.put(bg.a.class, new ew());
        hashMap.put(bh.class, new fb());
        hashMap.put(bh.b.class, new ey());
        hashMap.put(bh.d.class, new fa());
        hashMap.put(bh.c.class, new ez());
        hashMap.put(bi.class, new fc());
        hashMap.put(bj.class, new fi());
        hashMap.put(bk.class, new fd());
        hashMap.put(bl.class, new fe());
        hashMap.put(bm.class, new ff());
        hashMap.put(bn.class, new fg());
        hashMap.put(bo.class, new fh());
        hashMap.put(bp.class, new fj());
        hashMap.put(br.class, new fl());
        hashMap.put(bs.class, new fm());
        hashMap.put(bt.class, new fn());
        hashMap.put(bt.a.class, new fo());
        hashMap.put(bu.class, new fp());
        hashMap.put(bv.class, new fq());
        hashMap.put(bw.class, new fr());
        hashMap.put(bx.class, new fs());
        hashMap.put(by.class, new fv());
        hashMap.put(RoomNotifyMessageExtra.class, new fu());
        hashMap.put(RoomNotifyMessageExtra.Background.class, new ft());
        hashMap.put(bz.class, new fw());
        hashMap.put(ca.class, new fx());
        hashMap.put(cb.class, new fy());
        hashMap.put(cc.class, new fz());
        hashMap.put(cd.class, new ga());
        hashMap.put(ce.class, new gb());
        hashMap.put(cf.class, new gc());
        hashMap.put(ch.class, new ge());
        hashMap.put(ch.a.class, new gd());
        hashMap.put(ci.class, new gf());
        hashMap.put(cj.class, new gg());
        hashMap.put(ck.class, new gi());
        hashMap.put(ck.a.class, new gh());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.a.class, new com.bytedance.android.livesdk.model.message.b.t());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.b.class, new com.bytedance.android.livesdk.model.message.b.u());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.c.class, new com.bytedance.android.livesdk.model.message.b.v());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.d.class, new com.bytedance.android.livesdk.model.message.b.w());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.e.class, new com.bytedance.android.livesdk.model.message.b.x());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.f.class, new com.bytedance.android.livesdk.model.message.b.y());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.g.class, new com.bytedance.android.livesdk.model.message.b.z());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.j.class, new com.bytedance.android.livesdk.model.message.b.ac());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.q.class, new com.bytedance.android.livesdk.model.message.b.aj());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.a.class, new com.bytedance.android.livesdk.model.message.c.j());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.b.class, new com.bytedance.android.livesdk.model.message.c.r());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.c.class, new com.bytedance.android.livesdk.model.message.c.k());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.d.class, new com.bytedance.android.livesdk.model.message.c.q());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.e.class, new com.bytedance.android.livesdk.model.message.c.l());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.f.class, new com.bytedance.android.livesdk.model.message.c.m());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.g.class, new com.bytedance.android.livesdk.model.message.c.n());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.h.class, new com.bytedance.android.livesdk.model.message.c.o());
        hashMap.put(com.bytedance.android.livesdk.model.message.c.i.class, new com.bytedance.android.livesdk.model.message.c.p());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.a.a.class, new com.bytedance.android.livesdk.model.message.d.a.b());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.b.a.class, new com.bytedance.android.livesdk.model.message.d.b.b());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.c.a.class, new com.bytedance.android.livesdk.model.message.d.c.f());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.c.b.class, new com.bytedance.android.livesdk.model.message.d.c.g());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.c.c.class, new com.bytedance.android.livesdk.model.message.d.c.h());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.c.d.class, new com.bytedance.android.livesdk.model.message.d.c.i());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.d.a.class, new com.bytedance.android.livesdk.model.message.d.d.b());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.e.a.class, new com.bytedance.android.livesdk.model.message.d.e.b());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.f.a.class, new com.bytedance.android.livesdk.model.message.d.f.c());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.f.b.class, new com.bytedance.android.livesdk.model.message.d.f.d());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.i.a.class, new com.bytedance.android.livesdk.model.message.d.i.b());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.j.a.class, new com.bytedance.android.livesdk.model.message.d.j.b());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.k.a.class, new com.bytedance.android.livesdk.model.message.d.k.d());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.k.b.class, new com.bytedance.android.livesdk.model.message.d.k.e());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.k.c.class, new com.bytedance.android.livesdk.model.message.d.k.f());
        hashMap.put(com.bytedance.android.livesdk.model.c.class, new com.bytedance.android.livesdk.model.bd());
        hashMap.put(com.bytedance.android.livesdk.model.d.class, new com.bytedance.android.livesdk.model.be());
        hashMap.put(com.bytedance.android.livesdk.model.e.class, new bf());
        hashMap.put(com.bytedance.android.livesdk.model.g.class, new com.bytedance.android.livesdk.model.bg());
        hashMap.put(com.bytedance.android.livesdk.model.h.class, new com.bytedance.android.livesdk.model.bh());
        hashMap.put(com.bytedance.android.livesdk.model.i.class, new com.bytedance.android.livesdk.model.bj());
        hashMap.put(i.a.class, new com.bytedance.android.livesdk.model.bi());
        hashMap.put(com.bytedance.android.livesdk.model.j.class, new com.bytedance.android.livesdk.model.bk());
        hashMap.put(com.bytedance.android.livesdk.model.m.class, new com.bytedance.android.livesdk.model.bl());
        hashMap.put(FansClubData.class, new com.bytedance.android.livesdk.model.bm());
        hashMap.put(FansClubData.UserBadge.class, new com.bytedance.android.livesdk.model.bn());
        hashMap.put(FansClubMember.class, new com.bytedance.android.livesdk.model.bo());
        hashMap.put(com.bytedance.android.livesdk.model.n.class, new bq());
        hashMap.put(com.bytedance.android.livesdk.model.o.class, new com.bytedance.android.livesdk.model.bp());
        hashMap.put(FeedItem.class, new com.bytedance.android.livesdk.model.br());
        hashMap.put(com.bytedance.android.livesdk.model.u.class, new com.bytedance.android.livesdk.model.bx());
        hashMap.put(com.bytedance.android.livesdk.model.v.class, new com.bytedance.android.livesdk.model.bt());
        hashMap.put(GiftOperation.class, new com.bytedance.android.livesdk.model.bu());
        hashMap.put(com.bytedance.android.livesdk.model.w.class, new com.bytedance.android.livesdk.model.bv());
        hashMap.put(GiftTrayInfo.class, new com.bytedance.android.livesdk.model.bw());
        hashMap.put(com.bytedance.android.livesdk.model.y.class, new com.bytedance.android.livesdk.model.by());
        hashMap.put(com.bytedance.android.livesdk.model.ai.class, new com.bytedance.android.livesdk.model.ca());
        hashMap.put(com.bytedance.android.livesdk.model.al.class, new com.bytedance.android.livesdk.model.cb());
        hashMap.put(MaskLayer.class, new com.bytedance.android.livesdk.model.cc());
        hashMap.put(com.bytedance.android.livesdk.model.aq.class, new com.bytedance.android.livesdk.model.cd());
        hashMap.put(com.bytedance.android.livesdk.model.ar.class, new com.bytedance.android.livesdk.model.ce());
        hashMap.put(RoomAuthOffReasons.class, new com.bytedance.android.livesdk.model.cf());
        hashMap.put(RoomAuthStatus.class, new cg());
        hashMap.put(com.bytedance.android.livesdk.model.av.class, new com.bytedance.android.livesdk.model.ch());
        hashMap.put(RoomStats.class, new com.bytedance.android.livesdk.model.ci());
        hashMap.put(ShortTouchItem.class, new com.bytedance.android.livesdk.model.cj());
        hashMap.put(com.bytedance.android.livesdk.model.aw.class, new com.bytedance.android.livesdk.model.ck());
        hashMap.put(com.bytedance.android.livesdk.model.ay.class, new com.bytedance.android.livesdk.model.cl());
        hashMap.put(ba.class, new com.bytedance.android.livesdk.model.cn());
        hashMap.put(com.bytedance.android.livesdk.model.bb.class, new com.bytedance.android.livesdk.model.cm());
        hashMap.put(com.bytedance.android.livesdk.model.bc.class, new com.bytedance.android.livesdk.model.co());
        hashMap.put(WarningTag.class, new com.bytedance.android.livesdk.model.cp());
        hashMap.put(com.bytedance.android.livesdk.chatroom.interact.model.d.class, new com.bytedance.android.livesdk.chatroom.interact.model.m());
        hashMap.put(com.bytedance.android.livesdk.chatroom.interact.model.e.class, new com.bytedance.android.livesdk.chatroom.interact.model.n());
        hashMap.put(BALinkStruct.class, new com.bytedance.android.livesdkapi.depend.model.live.t());
        hashMap.put(CommerceStruct.class, new com.bytedance.android.livesdkapi.depend.model.live.w());
        hashMap.put(FeedRoomLabel.class, new com.bytedance.android.livesdkapi.depend.model.live.y());
        hashMap.put(LiveCoreSDKData.class, new com.bytedance.android.livesdkapi.depend.model.live.ab());
        hashMap.put(LiveCoreSDKData.PullData.class, new com.bytedance.android.livesdkapi.depend.model.live.ac());
        hashMap.put(LiveCoreSDKData.Options.class, new com.bytedance.android.livesdkapi.depend.model.live.aa());
        hashMap.put(LiveCoreSDKData.Quality.class, new com.bytedance.android.livesdkapi.depend.model.live.ad());
        hashMap.put(Room.class, new com.bytedance.android.livesdkapi.depend.model.live.al());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.p.class, new com.bytedance.android.livesdkapi.depend.model.live.ai());
        hashMap.put(StreamUrl.class, new com.bytedance.android.livesdkapi.depend.model.live.ao());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.s.class, new com.bytedance.android.livesdkapi.depend.model.live.am());
        hashMap.put(s.a.class, new com.bytedance.android.livesdkapi.depend.model.live.an());
        hashMap.put(com.bytedance.android.livesdkapi.h.b.class, new com.bytedance.android.livesdkapi.h.f());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.d.class, new com.bytedance.android.livesdkapi.depend.model.live.a.q());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.e.class, new com.bytedance.android.livesdkapi.depend.model.live.a.r());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.h.class, new com.bytedance.android.livesdkapi.depend.model.live.a.u());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.b.class, new com.bytedance.android.livesdkapi.depend.model.live.a.o());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.c.class, new com.bytedance.android.livesdkapi.depend.model.live.a.p());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.k.class, new com.bytedance.android.livesdkapi.depend.model.live.a.w());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.l.class, new com.bytedance.android.livesdkapi.depend.model.live.a.x());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.m.class, new com.bytedance.android.livesdkapi.depend.model.live.a.y());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.f.class, new com.bytedance.android.livesdkapi.depend.model.live.a.t());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.g.class, new com.bytedance.android.livesdkapi.depend.model.live.a.s());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.i.class, new com.bytedance.android.livesdkapi.depend.model.live.a.v());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.a.a.class, new com.bytedance.android.livesdkapi.depend.model.live.a.n());
        hashMap.put(ContinueRoomResponse.class, new com.bytedance.android.livesdkapi.depend.model.live.x());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.g.class, new com.bytedance.android.livesdkapi.depend.model.live.ae());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.d.class, new com.bytedance.android.livesdkapi.depend.model.live.z());
        hashMap.put(com.bytedance.android.livesdkapi.depend.model.live.h.class, new com.bytedance.android.livesdkapi.depend.model.live.af());
        hashMap.put(com.bytedance.android.livesdk.model.message.e.b.class, new com.bytedance.android.livesdk.model.message.e.d());
        hashMap.put(com.bytedance.android.livesdk.model.message.e.a.class, new com.bytedance.android.livesdk.model.message.e.c());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.g.a.class, new com.bytedance.android.livesdk.model.message.d.g.b());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.c.e.class, new com.bytedance.android.livesdk.model.message.d.c.j());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.h.a.class, new com.bytedance.android.livesdk.model.message.d.h.c());
        hashMap.put(com.bytedance.android.livesdk.model.message.d.h.b.class, new com.bytedance.android.livesdk.model.message.d.h.d());
        hashMap.put(com.bytedance.android.livesdk.model.message.u.class, new di());
        hashMap.put(com.bytedance.android.livesdk.model.message.f.class, new cs());
        hashMap.put(com.bytedance.android.livesdk.model.message.v.class, new dj());
        hashMap.put(com.bytedance.android.livesdk.model.message.w.class, new dk());
        hashMap.put(com.bytedance.android.livesdk.model.message.af.class, new dt());
        hashMap.put(com.bytedance.android.livesdk.model.message.au.class, new ek());
        hashMap.put(com.bytedance.android.livesdk.model.message.ba.class, new eq());
        hashMap.put(com.bytedance.android.livesdk.model.message.bf.class, new ev());
        hashMap.put(com.bytedance.android.livesdk.model.message.bq.class, new fk());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.h.class, new com.bytedance.android.livesdk.model.message.b.aa());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.l.class, new com.bytedance.android.livesdk.model.message.b.ae());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.m.class, new com.bytedance.android.livesdk.model.message.b.af());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.k.class, new com.bytedance.android.livesdk.model.message.b.ad());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.i.class, new com.bytedance.android.livesdk.model.message.b.ab());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.n.class, new com.bytedance.android.livesdk.model.message.b.ag());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.o.class, new com.bytedance.android.livesdk.model.message.b.ah());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.s.class, new com.bytedance.android.livesdk.model.message.b.al());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.p.class, new com.bytedance.android.livesdk.model.message.b.ai());
        hashMap.put(com.bytedance.android.livesdk.model.message.b.r.class, new com.bytedance.android.livesdk.model.message.b.ak());
        hashMap.put(GameTag.class, new com.bytedance.android.livesdk.model.bs());
        hashMap.put(Hashtag.class, new com.bytedance.android.livesdk.model.bz());
        hashMap.put(com.bytedance.android.livesdk.model.a.a.class, new com.bytedance.android.livesdk.model.a.e());
        hashMap.put(com.bytedance.android.livesdk.model.a.d.class, new com.bytedance.android.livesdk.model.a.h());
        hashMap.put(com.bytedance.android.livesdk.model.a.c.class, new com.bytedance.android.livesdk.model.a.g());
        hashMap.put(com.bytedance.android.livesdk.model.a.b.class, new com.bytedance.android.livesdk.model.a.f());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.c.a.class, new com.bytedance.android.livesdk.chatroom.model.c.d());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.c.c.class, new com.bytedance.android.livesdk.chatroom.model.c.f());
        hashMap.put(com.bytedance.android.livesdk.chatroom.model.c.b.class, new com.bytedance.android.livesdk.chatroom.model.c.e());
        com.bytedance.android.live.network.h.a().a(hashMap);
        com.bytedance.android.live.network.h.a().f12122a.putAll(hashMap2);
    }
}
