package com.ss.android.ugc.aweme.settingsrequest.a;

import com.bytedance.covode.number.Covode;
import com.bytedance.ies.abmock.SettingsManager;
import com.bytedance.ies.abmock.b;
import com.bytedance.ies.ugc.appcontext.g;
import com.bytedance.ies.ugc.aweme.commercialize.splash.core.SplashAdServiceImpl;
import com.bytedance.ies.ugc.aweme.commercialize.splash.service.ISplashAdService;
import com.bytedance.keva.Keva;
import com.ss.android.ugc.aweme.ay.e;
import com.ss.android.ugc.aweme.experiment.aa;
import com.ss.android.ugc.aweme.experiment.ab;
import com.ss.android.ugc.aweme.experiment.ac;
import com.ss.android.ugc.aweme.experiment.ad;
import com.ss.android.ugc.aweme.experiment.ae;
import com.ss.android.ugc.aweme.experiment.af;
import com.ss.android.ugc.aweme.experiment.ag;
import com.ss.android.ugc.aweme.experiment.ah;
import com.ss.android.ugc.aweme.experiment.aj;
import com.ss.android.ugc.aweme.experiment.ak;
import com.ss.android.ugc.aweme.experiment.al;
import com.ss.android.ugc.aweme.experiment.am;
import com.ss.android.ugc.aweme.experiment.an;
import com.ss.android.ugc.aweme.experiment.ao;
import com.ss.android.ugc.aweme.experiment.ap;
import com.ss.android.ugc.aweme.experiment.aq;
import com.ss.android.ugc.aweme.experiment.ar;
import com.ss.android.ugc.aweme.experiment.as;
import com.ss.android.ugc.aweme.experiment.at;
import com.ss.android.ugc.aweme.experiment.av;
import com.ss.android.ugc.aweme.experiment.ay;
import com.ss.android.ugc.aweme.experiment.az;
import com.ss.android.ugc.aweme.experiment.ba;
import com.ss.android.ugc.aweme.experiment.bb;
import com.ss.android.ugc.aweme.experiment.be;
import com.ss.android.ugc.aweme.experiment.bf;
import com.ss.android.ugc.aweme.experiment.bi;
import com.ss.android.ugc.aweme.experiment.bj;
import com.ss.android.ugc.aweme.experiment.bk;
import com.ss.android.ugc.aweme.experiment.bl;
import com.ss.android.ugc.aweme.experiment.bm;
import com.ss.android.ugc.aweme.experiment.bn;
import com.ss.android.ugc.aweme.experiment.bo;
import com.ss.android.ugc.aweme.experiment.bp;
import com.ss.android.ugc.aweme.experiment.bq;
import com.ss.android.ugc.aweme.experiment.br;
import com.ss.android.ugc.aweme.experiment.bs;
import com.ss.android.ugc.aweme.experiment.bt;
import com.ss.android.ugc.aweme.experiment.dh;
import com.ss.android.ugc.aweme.experiment.di;
import com.ss.android.ugc.aweme.experiment.dj;
import com.ss.android.ugc.aweme.experiment.dk;
import com.ss.android.ugc.aweme.experiment.dt;
import com.ss.android.ugc.aweme.experiment.eb;
import com.ss.android.ugc.aweme.experiment.eo;
import com.ss.android.ugc.aweme.experiment.gh;
import com.ss.android.ugc.aweme.experiment.hc;
import com.ss.android.ugc.aweme.experiment.hn;
import com.ss.android.ugc.aweme.experiment.hq;
import com.ss.android.ugc.aweme.experiment.hr;
import com.ss.android.ugc.aweme.experiment.hs;
import com.ss.android.ugc.aweme.experiment.s;
import com.ss.android.ugc.aweme.experiment.t;
import com.ss.android.ugc.aweme.experiment.u;
import com.ss.android.ugc.aweme.experiment.v;
import com.ss.android.ugc.aweme.experiment.w;
import com.ss.android.ugc.aweme.experiment.x;
import com.ss.android.ugc.aweme.experiment.y;
import com.ss.android.ugc.aweme.experiment.z;
import com.ss.android.ugc.aweme.language.d;
import com.ss.android.ugc.aweme.s.c;

public final class a {
    static {
        Covode.recordClassIndex(80887);
    }

    public static void a() {
        boolean z;
        Keva repo = Keva.getRepo("ab_repo_cold_boot");
        repo.storeInt("optimize_user_service", b.a().a(true, "optimize_user_service_option", 2));
        repo.storeInt("key_jato", b.a().a(true, "key_jato", 0));
        repo.storeInt("key_jato_gray_2130", b.a().a(true, "key_jato_gray_2130", 0));
        repo.storeBoolean("fresco_pie_decode_setting", e.a());
        repo.storeInt("key_preload_cache", b.a().a(true, "key_preload_cache", 0));
        repo.storeInt("key_preload_player", b.a().a(true, "key_preload_player", 0));
        repo.storeInt("key_prepare_video", b.a().a(true, "key_prepare_video", 0));
        repo.storeBoolean("feed_cache_delete_delay", b.a().a(true, "feed_cache_delete_delay", false));
        repo.storeInt("key_ipc_memory_cache", b.a().a(true, "ab_ipc_memory_cache", 0));
        repo.storeInt("key_ipc_memory_cache_timeout", b.a().a(true, "ab_ipc_memory_cache_timeout", 0));
        repo.storeInt("key_opt_precreate_lock", b.a().a(true, "key_opt_precreate_lock", 0));
        repo.storeInt("key_lego_thread", b.a().a(true, "lego_thread_num", 4));
        repo.storeInt("infra_cold_boot_opt", b.a().a(true, "infra_cold_boot_opt", 0));
        if (b.a().a(true, "new_fps", 0) == eo.f89951a) {
            z = true;
        } else {
            z = false;
        }
        repo.storeBoolean("key_new_fps", z);
        repo.storeInt("zl_async_inflate", b.a().a(true, "zl_async_inflate", 49));
        repo.storeBoolean("isInTikTokRegionForAbTestInit", d.c());
        repo.storeInt("downgrade_bg_experiment", b.a().a(true, "downgrade_bg_experiment", 0));
        repo.storeInt("is_opt_lego_schedule", b.a().a(true, "is_opt_lego_schedule", 2));
        repo.storeInt("is_opt_lego_add", b.a().a(true, "is_opt_lego_add", 0));
        repo.storeInt("lego_threadpool_type", b.a().a(true, "lego_threadpool_type", 11));
        repo.storeLong("lego_boot_finish_trigger_delay", SettingsManager.a().a("lego_boot_finish_trigger_delay", 1000L));
        repo.storeBoolean("lego_boot_finish_commit_opt", SettingsManager.a().a("lego_boot_finish_commit_opt", true));
        repo.storeLong("lego_boot_finish_sparse", SettingsManager.a().a("lego_boot_finish_sparse", 300L));
        repo.storeInt("cold_boot_opt_v3", b.a().a(true, "cold_boot_opt_v3", 5825));
        repo.storeInt("first_feed_ok", b.a().a(true, "first_feed_ok", 0));
        repo.storeInt("jump_cookie", b.a().a(true, "jump_cookie", 0));
        repo.storeInt("npth_refactor", b.a().a(true, "npth_refactor", 5));
        repo.storeInt("sky_eye_gson_flip", b.a().a(true, "sky_eye_gson_flip", 1));
        repo.storeInt("cold_boot_degradation", b.a().a(true, "cold_boot_degradation", 0));
        repo.storeInt("key_optimize_user_store", b.a().a(true, "optimize_user_store_option", 0));
        repo.storeInt("push_start_opt_v1", b.a().a(true, "push_start_opt_v1", 59));
        repo.storeInt("init_module_opt", b.a().a(true, "init_module_opt", 2));
        repo.storeInt("feed_preload_request", b.a().a(true, "feed_preload_request", 0));
        repo.storeInt("feed_preload_opt", b.a().a(true, "feed_preload_opt", 0));
        c.a(g.a(), "optimize_cold_boot_hook_app_context", ar.f89558a);
        c.a(g.a(), "optimize_kevaasync", at.f89562a);
        repo.storeBoolean("optimize_userstore_early", bt.f89621a);
        repo.storeBoolean("optimize_splashad_early", bq.f89618a);
        repo.storeBoolean("optimize_async_router", ac.f89522a);
        repo.storeBoolean("optimize_push_early", bp.f89617a);
        repo.storeBoolean("optimize_av_early", ad.f89523a);
        repo.storeBoolean("optimize_appfly_early", u.f90277a);
        repo.storeBoolean("optimize_async_abtask", s.f90275a);
        repo.storeBoolean("optimize_async_splitcompatinstall", bs.f89620a);
        repo.storeBoolean("optimize_preload_newuserjourney", bb.f89595a);
        repo.storeBoolean("optimize_newuserjourneyelaborate", ba.f89594a);
        bl.a();
        repo.storeBoolean("cold_boot_player_kit_init_task_async", b.a().a(true, "cold_boot_player_kit_init_task_async", false));
        repo.storeBoolean("optimize_godzilla_async", aq.f89557a);
        repo.storeBoolean("thread_stack_opt", b.a().a(true, "thread_stack_opt", true));
        az.a(b.a().a(true, "cold_boot_measure_opt", 1));
        com.ss.android.ugc.aweme.friends.service.a.f97047a.r();
        repo.storeInt("cold_boot_mainfragment_opt", b.a().a(true, "cold_boot_mainfragment_opt", 2));
        repo.storeBoolean("keva_multiple_memcache", b.a().a(true, "keva_multiple_memcache", true));
        repo.storeBoolean("no_network_opt", b.a().a(true, "no_network_opt", false));
        repo.storeBoolean("optimize_dead_system", SettingsManager.a().a("dead_system_solution", true));
        repo.storeBoolean("optimize_webview", SettingsManager.a().a("preload_webview", false));
        repo.storeBoolean("v1_uninstall_enable", b.a().a(true, "v1_uninstall_enable", true));
        repo.storeInt("cold_boot_optim_v1", b.a().a(true, "cold_boot_optim_v1", 0));
        repo.storeInt("cold_boot_optim_v2", b.a().a(true, "cold_boot_optim_v2", 0));
        repo.storeInt("delay_ttlivesdk", b.a().a(true, "delay_ttlivesdk", 1));
        repo.storeInt("enable_request_tag", b.a().a(true, "enable_request_tag", 0));
        repo.storeInt("is_small_task_opt", b.a().a(true, "is_small_task_opt", 0));
        repo.storeInt("cold_boot_mainfragment_opt", b.a().a(true, "cold_boot_mainfragment_opt", 2));
        repo.storeBoolean("keva_multiple_memcache", b.a().a(true, "keva_multiple_memcache", true));
        com.ss.android.ugc.aweme.story.g.f137757a.g();
        repo.storeInt("cold_boot_cpu_monitor", b.a().a(true, "cold_boot_cpu_monitor", 0));
        repo.storeInt("aot_delay_experiment", b.a().a(true, "aot_delay_experiment", 0));
        repo.storeInt("splash_opt", b.a().a(true, "splash_opt", 18));
        repo.storeInt("splash_new_factory_opt", b.a().a(true, "splash_new_factory_opt", 1));
        repo.storeInt("first_frame_do_frame_opt", b.a().a(true, "first_frame_do_frame_opt", 1));
        ISplashAdService h2 = SplashAdServiceImpl.h();
        if (h2 != null) {
            h2.g();
        }
        repo.storeBoolean("layoutinfalter_hook", b.a().a(true, "layoutinfalter_hook", false));
        repo.storeBoolean("passive_gecko_clean_enbled", b.a().a(true, "passive_gecko_clean_enbled", false));
        repo.storeInt("preload_feed_count", b.a().a(true, "preload_feed_count", 0));
        repo.storeBoolean("enable_fast_event_bus", b.a().a(true, "enable_fast_event_bus", false));
        repo.storeInt("feed_adapter_get_view_delay", ao.a());
        repo.storeInt("viewpager_load_delay_phase", ap.a());
        repo.storeBoolean("first_feed_msg_focus_send_opt", dj.f89788a);
        repo.storeBoolean("first_feed_msg_asynchronous_opt", di.f89787a);
        repo.storeBoolean("first_feed_msg_post_animation_opt", dk.f89789a);
        repo.storeBoolean("first_feed_dont_move_doframe_opt", dh.f89786a);
        repo.storeInt("is_downgrade_opt", b.a().a(true, "is_downgrade_opt", 112));
        repo.storeInt("is_downgrade_splite_opt", b.a().a(true, "is_downgrade_splite_opt", 0));
        repo.storeInt("appflyer_opt", b.a().a(true, "appflyer_opt", 0));
        repo.storeBoolean("is_big_core_bound", ag.f89530a);
        repo.storeInt("cold_boot_preload_class", b.a().a(true, "cold_boot_preload_class", 0));
        repo.storeInt("second_page_compile_opt", gh.f90141a);
        repo.storeBoolean("optimize_preloadtuxview", bm.f89614a);
        repo.storeBoolean("optimize_preloadviewelaborate", bn.f89615a);
        repo.storeBoolean("optimize_andinflatethread", t.f90276a);
        repo.storeBoolean("optimize_splashviewstub", br.f89619a);
        repo.storeInt("optimize_preloadfeedtype", bi.f89610a);
        repo.storeBoolean("optimize_asyncinflatefragmentmainpage", aa.f89520a);
        repo.storeBoolean("optimize_asyncinflatefragmentmain", z.f90282a);
        repo.storeBoolean("optimize_asyncinflatefragmentfeed", x.f90280a);
        repo.storeBoolean("optimize_asyncinflatefragmentfeedfollow", y.f90281a);
        repo.storeBoolean("optimize_asyncinflatecoldbootfinish", w.f90279a);
        repo.storeLong("optimize_asyncinflateprofiledelaytime", ab.f89521a);
        repo.storeBoolean("optimize_enablestorey", al.f89548a);
        repo.storeBoolean("optimize_publishtabelaborate", bo.f89616a);
        repo.storeBoolean("optimize_maintabstripelaborate", ay.f89580a);
        repo.storeBoolean("optimize_precreaterecommendfragment", bf.f89603a);
        repo.storeBoolean("optimize_precreatefollowfragment", be.f89602a);
        repo.storeBoolean("optimize_liveiconelaborate", av.f89566a);
        repo.storeBoolean("optimize_followbubble", an.f89550a);
        repo.storeBoolean("optimize_asynccheckfission", v.f90278a);
        repo.storeBoolean("optimize_feeddmtview", am.f89549a);
        repo.storeBoolean("optimize_preloadonlywifi", hq.f90228a);
        repo.storeBoolean("optimize_preloadvideocover", hs.f90230a);
        repo.storeBoolean("optimize_preloadallvideo", hr.f90229a);
        repo.storeInt("optimize_cachevideocount", hn.f90226a);
        repo.storeBoolean("hpas2sv_dialog_async", as.a());
        repo.storeInt("decorview_async_optim", ah.a());
        repo.storeInt("is_opt_lego_bootfinish", b.a().a(true, "is_opt_lego_bootfinish", 19));
        repo.storeInt("splash_downgrade", b.a().a(true, "splash_downgrade", 0));
        com.ss.android.ugc.aweme.utils.br.f142716a.b();
        repo.storeInt("lego_bootfinish_task_downgrade", b.a().a(true, "lego_bootfinish_task_downgrade", 64));
        repo.storeBoolean("optimize_deletefilesless128m", aj.f89546a);
        repo.storeBoolean("optimize_deletefilesless64m", ak.f89547a);
        repo.storeInt("fluency_insert_downgrade_opt", b.a().a(true, "fluency_insert_downgrade_opt", 3));
        repo.storeInt("widget_downgrade", b.a().a(true, "widget_downgrade", 0));
        repo.storeInt("ab_earse_opt", b.a().a(true, "ab_earse_opt", 0));
        repo.storeBoolean("codecoverage_enable", ae.a());
        repo.storeBoolean("codecoverage_memory_opt", af.a());
        repo.storeInt("prefetcher_cold_start", b.a().a(true, "prefetcher_cold_start", 0));
        repo.storeLong("prefetcher_step_size", b.a().a(true, "prefetcher_step_size", 524288L));
        repo.storeLong("prefetcher_step_sleep_duration", b.a().a(true, "prefetcher_step_sleep_duration", 15000L));
        repo.storeInt("applog_cold_boot_downgrade", b.a().a(true, "applog_cold_boot_downgrade", 0));
        repo.storeBoolean("grade_6_device", b.a().a(true, "grade_6_device", false));
        repo.storeInt("high_frequency_function_opt", b.a().a(true, "high_frequency_function_opt", 0));
        repo.storeBoolean("optimize_preloadplayerso", bk.f89612a);
        repo.storeInt("optimize_preloadplayerso_type", bk.f89613b);
        repo.storeBoolean("optimize_preloadinstance", bj.f89611a);
        repo.storeBoolean("optimize_kevaasync", at.f89562a);
        repo.storeInt("widget_lazy", b.a().a(true, "widget_lazy", 0));
        repo.storeInt("coldboot_mainact_task_exp", b.a().a(true, "coldboot_mainact_task_exp", 0));
        dt.b();
        repo.storeInt("app_widget_refactor_experiment", b.a().a(true, "app_widget_refactor_experiment", 0));
        repo.storeInt("player_resume_experiment", b.a().a(true, "player_resume_experiment", 0));
        repo.storeInt("main_looper_private_repo_opt_enable", b.a().a(true, "main_looper_private_opt_switch", 0));
        com.ss.android.ugc.aweme.legoImp.task.b.a();
        eb.b(com.bytedance.ies.ugc.appcontext.d.a());
        repo.storeBoolean("tryplay_preexecute", hc.a());
        repo.storeInt("settings_manager_notify_settings_experiment", b.a().a(true, "settings_manager_notify_settings_experiment", 0));
        repo.storeInt("system_launch_indicator_experiment", b.a().a(true, "system_launch_indicator_experiment", 0));
        repo.storeInt("use_BDXBridgeSDK", b.a().a(true, "use_BDXBridgeSDK", 0));
        repo.storeInt("use_BDXBridgeSDK_lynx", b.a().a(true, "use_BDXBridgeSDK_lynx", 0));
    }
}
